// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Troonch.Sales.DataAccess;

#nullable disable

namespace Troonch.RetailSales.Product.DataAccess.Migrations
{
    [DbContext(typeof(RetailSalesProductDataContext))]
    partial class RetailSalesProductDataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Troonch.Sales.Domain.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("CoverImageLink")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsPublished")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<Guid>("ProductBrandId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ProductCategoryId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ProductGenderId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("ProductMaterialId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("UpdatedOn")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("CoverImageLink")
                        .IsUnique();

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("ProductBrandId");

                    b.HasIndex("ProductCategoryId");

                    b.HasIndex("ProductGenderId");

                    b.HasIndex("ProductMaterialId");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Products");
                });

            modelBuilder.Entity("Troonch.Sales.Domain.Entities.ProductBrand", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(128)
                        .IsUnicode(true)
                        .HasColumnType("varchar(128)");

                    b.Property<DateTime>("UpdatedOn")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("ProductBrands");
                });

            modelBuilder.Entity("Troonch.Sales.Domain.Entities.ProductCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<Guid>("ProductSizeTypeId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("UpdatedOn")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.HasIndex("ProductSizeTypeId");

                    b.ToTable("ProductCategories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b8b85712-423a-48eb-9b9c-79cca44b55e1"),
                            CreatedOn = new DateTime(2024, 7, 7, 10, 34, 51, 230, DateTimeKind.Utc).AddTicks(6272),
                            Name = "Abiti - Completi",
                            ProductSizeTypeId = new Guid("b6829a28-318b-46ff-a059-d6f91743f92c"),
                            UpdatedOn = new DateTime(2024, 7, 7, 10, 34, 51, 230, DateTimeKind.Utc).AddTicks(6272)
                        },
                        new
                        {
                            Id = new Guid("a044d4fa-a88e-4c6d-82d8-b9df2a11b5e4"),
                            CreatedOn = new DateTime(2024, 7, 7, 10, 34, 51, 230, DateTimeKind.Utc).AddTicks(6276),
                            Name = "Giubbino",
                            ProductSizeTypeId = new Guid("b6829a28-318b-46ff-a059-d6f91743f92c"),
                            UpdatedOn = new DateTime(2024, 7, 7, 10, 34, 51, 230, DateTimeKind.Utc).AddTicks(6276)
                        },
                        new
                        {
                            Id = new Guid("16a9a771-61df-492f-ac71-41ced5867920"),
                            CreatedOn = new DateTime(2024, 7, 7, 10, 34, 51, 230, DateTimeKind.Utc).AddTicks(6279),
                            Name = "Felpa",
                            ProductSizeTypeId = new Guid("b6829a28-318b-46ff-a059-d6f91743f92c"),
                            UpdatedOn = new DateTime(2024, 7, 7, 10, 34, 51, 230, DateTimeKind.Utc).AddTicks(6279)
                        },
                        new
                        {
                            Id = new Guid("797db858-df20-46a1-b8da-2cfd2ec636af"),
                            CreatedOn = new DateTime(2024, 7, 7, 10, 34, 51, 230, DateTimeKind.Utc).AddTicks(6282),
                            Name = "Jeans",
                            ProductSizeTypeId = new Guid("b6829a28-318b-46ff-a059-d6f91743f92c"),
                            UpdatedOn = new DateTime(2024, 7, 7, 10, 34, 51, 230, DateTimeKind.Utc).AddTicks(6282)
                        },
                        new
                        {
                            Id = new Guid("cad9bd4c-169c-45a7-8de5-3107f4472f05"),
                            CreatedOn = new DateTime(2024, 7, 7, 10, 34, 51, 230, DateTimeKind.Utc).AddTicks(6284),
                            Name = "Cardigan",
                            ProductSizeTypeId = new Guid("b6829a28-318b-46ff-a059-d6f91743f92c"),
                            UpdatedOn = new DateTime(2024, 7, 7, 10, 34, 51, 230, DateTimeKind.Utc).AddTicks(6285)
                        },
                        new
                        {
                            Id = new Guid("dd4fe056-c02f-4479-9e5c-e9b603d2e878"),
                            CreatedOn = new DateTime(2024, 7, 7, 10, 34, 51, 230, DateTimeKind.Utc).AddTicks(6288),
                            Name = "Pigiama",
                            ProductSizeTypeId = new Guid("b6829a28-318b-46ff-a059-d6f91743f92c"),
                            UpdatedOn = new DateTime(2024, 7, 7, 10, 34, 51, 230, DateTimeKind.Utc).AddTicks(6289)
                        },
                        new
                        {
                            Id = new Guid("18325a35-5823-4107-93c2-0a557a3da158"),
                            CreatedOn = new DateTime(2024, 7, 7, 10, 34, 51, 230, DateTimeKind.Utc).AddTicks(6311),
                            Name = "Top",
                            ProductSizeTypeId = new Guid("b6829a28-318b-46ff-a059-d6f91743f92c"),
                            UpdatedOn = new DateTime(2024, 7, 7, 10, 34, 51, 230, DateTimeKind.Utc).AddTicks(6312)
                        },
                        new
                        {
                            Id = new Guid("d3417860-6f04-4126-8e8b-0953d3062822"),
                            CreatedOn = new DateTime(2024, 7, 7, 10, 34, 51, 230, DateTimeKind.Utc).AddTicks(6317),
                            Name = "Maglie",
                            ProductSizeTypeId = new Guid("b6829a28-318b-46ff-a059-d6f91743f92c"),
                            UpdatedOn = new DateTime(2024, 7, 7, 10, 34, 51, 230, DateTimeKind.Utc).AddTicks(6317)
                        },
                        new
                        {
                            Id = new Guid("14c881c8-b508-4d1b-a962-1f7ccde55ad2"),
                            CreatedOn = new DateTime(2024, 7, 7, 10, 34, 51, 230, DateTimeKind.Utc).AddTicks(6320),
                            Name = "Pantaloni",
                            ProductSizeTypeId = new Guid("b6829a28-318b-46ff-a059-d6f91743f92c"),
                            UpdatedOn = new DateTime(2024, 7, 7, 10, 34, 51, 230, DateTimeKind.Utc).AddTicks(6320)
                        },
                        new
                        {
                            Id = new Guid("f3fe7773-0b30-493c-b0be-1741a3fa5b19"),
                            CreatedOn = new DateTime(2024, 7, 7, 10, 34, 51, 230, DateTimeKind.Utc).AddTicks(6324),
                            Name = "Salopette",
                            ProductSizeTypeId = new Guid("b6829a28-318b-46ff-a059-d6f91743f92c"),
                            UpdatedOn = new DateTime(2024, 7, 7, 10, 34, 51, 230, DateTimeKind.Utc).AddTicks(6324)
                        },
                        new
                        {
                            Id = new Guid("8a58f41b-69af-44d0-af4e-a59f46c1805d"),
                            CreatedOn = new DateTime(2024, 7, 7, 10, 34, 51, 230, DateTimeKind.Utc).AddTicks(6327),
                            Name = "Camicia",
                            ProductSizeTypeId = new Guid("b6829a28-318b-46ff-a059-d6f91743f92c"),
                            UpdatedOn = new DateTime(2024, 7, 7, 10, 34, 51, 230, DateTimeKind.Utc).AddTicks(6327)
                        },
                        new
                        {
                            Id = new Guid("a830bddd-5ff9-4a66-a4df-989b1b9fa972"),
                            CreatedOn = new DateTime(2024, 7, 7, 10, 34, 51, 230, DateTimeKind.Utc).AddTicks(6330),
                            Name = "Shorts",
                            ProductSizeTypeId = new Guid("b6829a28-318b-46ff-a059-d6f91743f92c"),
                            UpdatedOn = new DateTime(2024, 7, 7, 10, 34, 51, 230, DateTimeKind.Utc).AddTicks(6330)
                        },
                        new
                        {
                            Id = new Guid("8b6dc331-1dcd-4646-b236-820846463cb3"),
                            CreatedOn = new DateTime(2024, 7, 7, 10, 34, 51, 230, DateTimeKind.Utc).AddTicks(6342),
                            Name = "Giacche | Trench",
                            ProductSizeTypeId = new Guid("9fe00ea4-831a-4044-b45b-556c81017fff"),
                            UpdatedOn = new DateTime(2024, 7, 7, 10, 34, 51, 230, DateTimeKind.Utc).AddTicks(6342)
                        },
                        new
                        {
                            Id = new Guid("74d8ac55-ea95-4fe9-94b9-9fa4d681f6a2"),
                            CreatedOn = new DateTime(2024, 7, 7, 10, 34, 51, 230, DateTimeKind.Utc).AddTicks(6346),
                            Name = "Blazer | Gilet",
                            ProductSizeTypeId = new Guid("9fe00ea4-831a-4044-b45b-556c81017fff"),
                            UpdatedOn = new DateTime(2024, 7, 7, 10, 34, 51, 230, DateTimeKind.Utc).AddTicks(6346)
                        },
                        new
                        {
                            Id = new Guid("efedaaea-8c70-4880-8030-5bbf22b152f8"),
                            CreatedOn = new DateTime(2024, 7, 7, 10, 34, 51, 230, DateTimeKind.Utc).AddTicks(6349),
                            Name = "Vestiti",
                            ProductSizeTypeId = new Guid("9fe00ea4-831a-4044-b45b-556c81017fff"),
                            UpdatedOn = new DateTime(2024, 7, 7, 10, 34, 51, 230, DateTimeKind.Utc).AddTicks(6349)
                        },
                        new
                        {
                            Id = new Guid("094d67e4-873d-4464-8ef9-19c311c7f39f"),
                            CreatedOn = new DateTime(2024, 7, 7, 10, 34, 51, 230, DateTimeKind.Utc).AddTicks(6354),
                            Name = "Body | Top",
                            ProductSizeTypeId = new Guid("9fe00ea4-831a-4044-b45b-556c81017fff"),
                            UpdatedOn = new DateTime(2024, 7, 7, 10, 34, 51, 230, DateTimeKind.Utc).AddTicks(6354)
                        },
                        new
                        {
                            Id = new Guid("1ad7ee6c-0731-4209-8112-08614df16b2a"),
                            CreatedOn = new DateTime(2024, 7, 7, 10, 34, 51, 230, DateTimeKind.Utc).AddTicks(6357),
                            Name = "Camicie",
                            ProductSizeTypeId = new Guid("9fe00ea4-831a-4044-b45b-556c81017fff"),
                            UpdatedOn = new DateTime(2024, 7, 7, 10, 34, 51, 230, DateTimeKind.Utc).AddTicks(6357)
                        },
                        new
                        {
                            Id = new Guid("d15894fb-11a2-4ac3-839b-bc774713d286"),
                            CreatedOn = new DateTime(2024, 7, 7, 10, 34, 51, 230, DateTimeKind.Utc).AddTicks(6361),
                            Name = "Magliette",
                            ProductSizeTypeId = new Guid("9fe00ea4-831a-4044-b45b-556c81017fff"),
                            UpdatedOn = new DateTime(2024, 7, 7, 10, 34, 51, 230, DateTimeKind.Utc).AddTicks(6361)
                        },
                        new
                        {
                            Id = new Guid("a1d471df-5975-4aaa-85b9-0ee4480c7551"),
                            CreatedOn = new DateTime(2024, 7, 7, 10, 34, 51, 230, DateTimeKind.Utc).AddTicks(6364),
                            Name = "Felpe",
                            ProductSizeTypeId = new Guid("9fe00ea4-831a-4044-b45b-556c81017fff"),
                            UpdatedOn = new DateTime(2024, 7, 7, 10, 34, 51, 230, DateTimeKind.Utc).AddTicks(6364)
                        },
                        new
                        {
                            Id = new Guid("7c1c1b98-a0ec-4818-8262-437167412410"),
                            CreatedOn = new DateTime(2024, 7, 7, 10, 34, 51, 230, DateTimeKind.Utc).AddTicks(6367),
                            Name = "Gonne",
                            ProductSizeTypeId = new Guid("9fe00ea4-831a-4044-b45b-556c81017fff"),
                            UpdatedOn = new DateTime(2024, 7, 7, 10, 34, 51, 230, DateTimeKind.Utc).AddTicks(6367)
                        },
                        new
                        {
                            Id = new Guid("bb953d24-bde4-4066-b3b3-573290ffd6d5"),
                            CreatedOn = new DateTime(2024, 7, 7, 10, 34, 51, 230, DateTimeKind.Utc).AddTicks(6370),
                            Name = "Shorts",
                            ProductSizeTypeId = new Guid("9fe00ea4-831a-4044-b45b-556c81017fff"),
                            UpdatedOn = new DateTime(2024, 7, 7, 10, 34, 51, 230, DateTimeKind.Utc).AddTicks(6370)
                        },
                        new
                        {
                            Id = new Guid("35fb8d42-dee9-46cb-bd4c-7e5b7328abdb"),
                            CreatedOn = new DateTime(2024, 7, 7, 10, 34, 51, 230, DateTimeKind.Utc).AddTicks(6373),
                            Name = "Pantaloni",
                            ProductSizeTypeId = new Guid("9fe00ea4-831a-4044-b45b-556c81017fff"),
                            UpdatedOn = new DateTime(2024, 7, 7, 10, 34, 51, 230, DateTimeKind.Utc).AddTicks(6373)
                        },
                        new
                        {
                            Id = new Guid("e59b116f-7e76-49c3-9253-841307f8a974"),
                            CreatedOn = new DateTime(2024, 7, 7, 10, 34, 51, 230, DateTimeKind.Utc).AddTicks(6376),
                            Name = "Jeans",
                            ProductSizeTypeId = new Guid("9fe00ea4-831a-4044-b45b-556c81017fff"),
                            UpdatedOn = new DateTime(2024, 7, 7, 10, 34, 51, 230, DateTimeKind.Utc).AddTicks(6377)
                        },
                        new
                        {
                            Id = new Guid("308d3fb9-6206-4c0d-9727-97524afd0878"),
                            CreatedOn = new DateTime(2024, 7, 7, 10, 34, 51, 230, DateTimeKind.Utc).AddTicks(6381),
                            Name = "Intimo",
                            ProductSizeTypeId = new Guid("9fe00ea4-831a-4044-b45b-556c81017fff"),
                            UpdatedOn = new DateTime(2024, 7, 7, 10, 34, 51, 230, DateTimeKind.Utc).AddTicks(6381)
                        },
                        new
                        {
                            Id = new Guid("c6f12a49-7ce5-433a-a34c-f700dcdc3522"),
                            CreatedOn = new DateTime(2024, 7, 7, 10, 34, 51, 230, DateTimeKind.Utc).AddTicks(6384),
                            Name = "Costumi da Bagno",
                            ProductSizeTypeId = new Guid("9fe00ea4-831a-4044-b45b-556c81017fff"),
                            UpdatedOn = new DateTime(2024, 7, 7, 10, 34, 51, 230, DateTimeKind.Utc).AddTicks(6384)
                        },
                        new
                        {
                            Id = new Guid("e954e82a-64b9-41b3-9b8d-c15381af0897"),
                            CreatedOn = new DateTime(2024, 7, 7, 10, 34, 51, 230, DateTimeKind.Utc).AddTicks(6387),
                            Name = "Polo",
                            ProductSizeTypeId = new Guid("9fe00ea4-831a-4044-b45b-556c81017fff"),
                            UpdatedOn = new DateTime(2024, 7, 7, 10, 34, 51, 230, DateTimeKind.Utc).AddTicks(6387)
                        },
                        new
                        {
                            Id = new Guid("7033555a-7b08-464a-96d9-c77de5ed1194"),
                            CreatedOn = new DateTime(2024, 7, 7, 10, 34, 51, 230, DateTimeKind.Utc).AddTicks(6390),
                            Name = "Maglioncini",
                            ProductSizeTypeId = new Guid("9fe00ea4-831a-4044-b45b-556c81017fff"),
                            UpdatedOn = new DateTime(2024, 7, 7, 10, 34, 51, 230, DateTimeKind.Utc).AddTicks(6390)
                        },
                        new
                        {
                            Id = new Guid("8e43cae0-2987-4f3f-822e-63780d214923"),
                            CreatedOn = new DateTime(2024, 7, 7, 10, 34, 51, 230, DateTimeKind.Utc).AddTicks(6402),
                            Name = "Borse",
                            ProductSizeTypeId = new Guid("e9424a4f-c953-4a93-ba77-bfbe21ae43e7"),
                            UpdatedOn = new DateTime(2024, 7, 7, 10, 34, 51, 230, DateTimeKind.Utc).AddTicks(6402)
                        },
                        new
                        {
                            Id = new Guid("aa5112f0-de8e-473e-867b-d4c8f040c197"),
                            CreatedOn = new DateTime(2024, 7, 7, 10, 34, 51, 230, DateTimeKind.Utc).AddTicks(6405),
                            Name = "Gioielli",
                            ProductSizeTypeId = new Guid("e9424a4f-c953-4a93-ba77-bfbe21ae43e7"),
                            UpdatedOn = new DateTime(2024, 7, 7, 10, 34, 51, 230, DateTimeKind.Utc).AddTicks(6406)
                        },
                        new
                        {
                            Id = new Guid("29fefa8a-ab30-4c63-a311-75b79ed29cc7"),
                            CreatedOn = new DateTime(2024, 7, 7, 10, 34, 51, 230, DateTimeKind.Utc).AddTicks(6409),
                            Name = "Occhiali da Sole",
                            ProductSizeTypeId = new Guid("e9424a4f-c953-4a93-ba77-bfbe21ae43e7"),
                            UpdatedOn = new DateTime(2024, 7, 7, 10, 34, 51, 230, DateTimeKind.Utc).AddTicks(6409)
                        },
                        new
                        {
                            Id = new Guid("58b8a6d4-2bb3-425e-a41e-ed8afd2dcad3"),
                            CreatedOn = new DateTime(2024, 7, 7, 10, 34, 51, 230, DateTimeKind.Utc).AddTicks(6411),
                            Name = "Cappelli",
                            ProductSizeTypeId = new Guid("e9424a4f-c953-4a93-ba77-bfbe21ae43e7"),
                            UpdatedOn = new DateTime(2024, 7, 7, 10, 34, 51, 230, DateTimeKind.Utc).AddTicks(6412)
                        },
                        new
                        {
                            Id = new Guid("70937125-1f64-4956-9ae4-562623eff181"),
                            CreatedOn = new DateTime(2024, 7, 7, 10, 34, 51, 230, DateTimeKind.Utc).AddTicks(6416),
                            Name = "Foulard",
                            ProductSizeTypeId = new Guid("e9424a4f-c953-4a93-ba77-bfbe21ae43e7"),
                            UpdatedOn = new DateTime(2024, 7, 7, 10, 34, 51, 230, DateTimeKind.Utc).AddTicks(6416)
                        },
                        new
                        {
                            Id = new Guid("ab1e2736-fa87-47f8-b554-f41497fe95e7"),
                            CreatedOn = new DateTime(2024, 7, 7, 10, 34, 51, 230, DateTimeKind.Utc).AddTicks(6419),
                            Name = "Cinture",
                            ProductSizeTypeId = new Guid("e9424a4f-c953-4a93-ba77-bfbe21ae43e7"),
                            UpdatedOn = new DateTime(2024, 7, 7, 10, 34, 51, 230, DateTimeKind.Utc).AddTicks(6419)
                        },
                        new
                        {
                            Id = new Guid("51d479d4-98c6-4d56-9f0a-e7e71dfe1d23"),
                            CreatedOn = new DateTime(2024, 7, 7, 10, 34, 51, 230, DateTimeKind.Utc).AddTicks(6423),
                            Name = "Orologi",
                            ProductSizeTypeId = new Guid("e9424a4f-c953-4a93-ba77-bfbe21ae43e7"),
                            UpdatedOn = new DateTime(2024, 7, 7, 10, 34, 51, 230, DateTimeKind.Utc).AddTicks(6423)
                        },
                        new
                        {
                            Id = new Guid("2d1fe279-74ca-47f5-8acf-4e2071892f63"),
                            CreatedOn = new DateTime(2024, 7, 7, 10, 34, 51, 230, DateTimeKind.Utc).AddTicks(6426),
                            Name = "Portafogli",
                            ProductSizeTypeId = new Guid("e9424a4f-c953-4a93-ba77-bfbe21ae43e7"),
                            UpdatedOn = new DateTime(2024, 7, 7, 10, 34, 51, 230, DateTimeKind.Utc).AddTicks(6426)
                        },
                        new
                        {
                            Id = new Guid("1a4048d6-9916-49fd-adb3-41a8155d8089"),
                            CreatedOn = new DateTime(2024, 7, 7, 10, 34, 51, 230, DateTimeKind.Utc).AddTicks(6428),
                            Name = "Sciarpe",
                            ProductSizeTypeId = new Guid("e9424a4f-c953-4a93-ba77-bfbe21ae43e7"),
                            UpdatedOn = new DateTime(2024, 7, 7, 10, 34, 51, 230, DateTimeKind.Utc).AddTicks(6428)
                        },
                        new
                        {
                            Id = new Guid("43ebb7cc-8b27-4712-9a53-2816b4c5e1fd"),
                            CreatedOn = new DateTime(2024, 7, 7, 10, 34, 51, 230, DateTimeKind.Utc).AddTicks(6431),
                            Name = "Guanti",
                            ProductSizeTypeId = new Guid("e9424a4f-c953-4a93-ba77-bfbe21ae43e7"),
                            UpdatedOn = new DateTime(2024, 7, 7, 10, 34, 51, 230, DateTimeKind.Utc).AddTicks(6431)
                        },
                        new
                        {
                            Id = new Guid("aa72f2c0-3146-44d4-9408-ccb6fe130cc3"),
                            CreatedOn = new DateTime(2024, 7, 7, 10, 34, 51, 230, DateTimeKind.Utc).AddTicks(6434),
                            Name = "Ombrelli",
                            ProductSizeTypeId = new Guid("e9424a4f-c953-4a93-ba77-bfbe21ae43e7"),
                            UpdatedOn = new DateTime(2024, 7, 7, 10, 34, 51, 230, DateTimeKind.Utc).AddTicks(6434)
                        },
                        new
                        {
                            Id = new Guid("83db5f0a-b4b4-4fb7-9df3-aed888e9d15a"),
                            CreatedOn = new DateTime(2024, 7, 7, 10, 34, 51, 230, DateTimeKind.Utc).AddTicks(6456),
                            Name = "Sneakers",
                            ProductSizeTypeId = new Guid("30622354-36db-4221-9903-d3a633b25b26"),
                            UpdatedOn = new DateTime(2024, 7, 7, 10, 34, 51, 230, DateTimeKind.Utc).AddTicks(6457)
                        },
                        new
                        {
                            Id = new Guid("cfce6141-6ac1-410b-9fe7-5fe027a8837d"),
                            CreatedOn = new DateTime(2024, 7, 7, 10, 34, 51, 230, DateTimeKind.Utc).AddTicks(6463),
                            Name = "Sandali",
                            ProductSizeTypeId = new Guid("30622354-36db-4221-9903-d3a633b25b26"),
                            UpdatedOn = new DateTime(2024, 7, 7, 10, 34, 51, 230, DateTimeKind.Utc).AddTicks(6463)
                        },
                        new
                        {
                            Id = new Guid("b58cfc64-d6e4-454b-9dac-846b13503ca6"),
                            CreatedOn = new DateTime(2024, 7, 7, 10, 34, 51, 230, DateTimeKind.Utc).AddTicks(6466),
                            Name = "Tacchi",
                            ProductSizeTypeId = new Guid("30622354-36db-4221-9903-d3a633b25b26"),
                            UpdatedOn = new DateTime(2024, 7, 7, 10, 34, 51, 230, DateTimeKind.Utc).AddTicks(6467)
                        },
                        new
                        {
                            Id = new Guid("a319f384-e662-47dc-b1c0-78068c1329a9"),
                            CreatedOn = new DateTime(2024, 7, 7, 10, 34, 51, 230, DateTimeKind.Utc).AddTicks(6470),
                            Name = "Ciabatte",
                            ProductSizeTypeId = new Guid("30622354-36db-4221-9903-d3a633b25b26"),
                            UpdatedOn = new DateTime(2024, 7, 7, 10, 34, 51, 230, DateTimeKind.Utc).AddTicks(6470)
                        },
                        new
                        {
                            Id = new Guid("2e0928c7-8d38-44e6-93f7-5e2fdaddeed7"),
                            CreatedOn = new DateTime(2024, 7, 7, 10, 34, 51, 230, DateTimeKind.Utc).AddTicks(6473),
                            Name = "Stivaletti",
                            ProductSizeTypeId = new Guid("30622354-36db-4221-9903-d3a633b25b26"),
                            UpdatedOn = new DateTime(2024, 7, 7, 10, 34, 51, 230, DateTimeKind.Utc).AddTicks(6473)
                        },
                        new
                        {
                            Id = new Guid("a538f018-dc1d-4970-a63e-ed76abb60015"),
                            CreatedOn = new DateTime(2024, 7, 7, 10, 34, 51, 230, DateTimeKind.Utc).AddTicks(6476),
                            Name = "Stivali",
                            ProductSizeTypeId = new Guid("30622354-36db-4221-9903-d3a633b25b26"),
                            UpdatedOn = new DateTime(2024, 7, 7, 10, 34, 51, 230, DateTimeKind.Utc).AddTicks(6477)
                        },
                        new
                        {
                            Id = new Guid("ff47760a-9017-4890-8740-d7b5669c1a73"),
                            CreatedOn = new DateTime(2024, 7, 7, 10, 34, 51, 230, DateTimeKind.Utc).AddTicks(6479),
                            Name = "Ballerine",
                            ProductSizeTypeId = new Guid("30622354-36db-4221-9903-d3a633b25b26"),
                            UpdatedOn = new DateTime(2024, 7, 7, 10, 34, 51, 230, DateTimeKind.Utc).AddTicks(6480)
                        },
                        new
                        {
                            Id = new Guid("febb6fae-21be-406d-b1b5-4d94cf8a3dcd"),
                            CreatedOn = new DateTime(2024, 7, 7, 10, 34, 51, 230, DateTimeKind.Utc).AddTicks(6482),
                            Name = "Mare",
                            ProductSizeTypeId = new Guid("30622354-36db-4221-9903-d3a633b25b26"),
                            UpdatedOn = new DateTime(2024, 7, 7, 10, 34, 51, 230, DateTimeKind.Utc).AddTicks(6483)
                        },
                        new
                        {
                            Id = new Guid("93e1addc-4c53-4177-b3db-725d306da8e4"),
                            CreatedOn = new DateTime(2024, 7, 7, 10, 34, 51, 230, DateTimeKind.Utc).AddTicks(6485),
                            Name = "Mocassini",
                            ProductSizeTypeId = new Guid("30622354-36db-4221-9903-d3a633b25b26"),
                            UpdatedOn = new DateTime(2024, 7, 7, 10, 34, 51, 230, DateTimeKind.Utc).AddTicks(6486)
                        },
                        new
                        {
                            Id = new Guid("3a25a489-136b-4d82-9d12-fca079ecdad1"),
                            CreatedOn = new DateTime(2024, 7, 7, 10, 34, 51, 230, DateTimeKind.Utc).AddTicks(6490),
                            Name = "Basse",
                            ProductSizeTypeId = new Guid("30622354-36db-4221-9903-d3a633b25b26"),
                            UpdatedOn = new DateTime(2024, 7, 7, 10, 34, 51, 230, DateTimeKind.Utc).AddTicks(6490)
                        },
                        new
                        {
                            Id = new Guid("c93e64a9-2d96-400b-b80f-9a9f6df704ff"),
                            CreatedOn = new DateTime(2024, 7, 7, 10, 34, 51, 230, DateTimeKind.Utc).AddTicks(6493),
                            Name = "Cerimonia",
                            ProductSizeTypeId = new Guid("30622354-36db-4221-9903-d3a633b25b26"),
                            UpdatedOn = new DateTime(2024, 7, 7, 10, 34, 51, 230, DateTimeKind.Utc).AddTicks(6493)
                        },
                        new
                        {
                            Id = new Guid("7d05707f-7261-4a28-b616-2869109e4ede"),
                            CreatedOn = new DateTime(2024, 7, 7, 10, 34, 51, 230, DateTimeKind.Utc).AddTicks(6503),
                            Name = "Sneakers",
                            ProductSizeTypeId = new Guid("91fab09e-daf4-477c-b585-8621021a85f3"),
                            UpdatedOn = new DateTime(2024, 7, 7, 10, 34, 51, 230, DateTimeKind.Utc).AddTicks(6503)
                        },
                        new
                        {
                            Id = new Guid("2dda20b1-9b84-4eea-812c-ab281088f828"),
                            CreatedOn = new DateTime(2024, 7, 7, 10, 34, 51, 230, DateTimeKind.Utc).AddTicks(6506),
                            Name = "Sandali",
                            ProductSizeTypeId = new Guid("91fab09e-daf4-477c-b585-8621021a85f3"),
                            UpdatedOn = new DateTime(2024, 7, 7, 10, 34, 51, 230, DateTimeKind.Utc).AddTicks(6506)
                        },
                        new
                        {
                            Id = new Guid("2f6f27db-3de4-47fb-b61b-2662f515954f"),
                            CreatedOn = new DateTime(2024, 7, 7, 10, 34, 51, 230, DateTimeKind.Utc).AddTicks(6509),
                            Name = "Ciabatte",
                            ProductSizeTypeId = new Guid("91fab09e-daf4-477c-b585-8621021a85f3"),
                            UpdatedOn = new DateTime(2024, 7, 7, 10, 34, 51, 230, DateTimeKind.Utc).AddTicks(6509)
                        },
                        new
                        {
                            Id = new Guid("f3f28a16-0b68-4246-9e5f-edeec97043b6"),
                            CreatedOn = new DateTime(2024, 7, 7, 10, 34, 51, 230, DateTimeKind.Utc).AddTicks(6512),
                            Name = "Stivaletti",
                            ProductSizeTypeId = new Guid("91fab09e-daf4-477c-b585-8621021a85f3"),
                            UpdatedOn = new DateTime(2024, 7, 7, 10, 34, 51, 230, DateTimeKind.Utc).AddTicks(6512)
                        },
                        new
                        {
                            Id = new Guid("d4f5635b-f782-4f68-9ba5-c9b8372f957d"),
                            CreatedOn = new DateTime(2024, 7, 7, 10, 34, 51, 230, DateTimeKind.Utc).AddTicks(6514),
                            Name = "Stivali",
                            ProductSizeTypeId = new Guid("91fab09e-daf4-477c-b585-8621021a85f3"),
                            UpdatedOn = new DateTime(2024, 7, 7, 10, 34, 51, 230, DateTimeKind.Utc).AddTicks(6515)
                        },
                        new
                        {
                            Id = new Guid("a3bb88cf-8979-438b-89d9-d5f59fee02de"),
                            CreatedOn = new DateTime(2024, 7, 7, 10, 34, 51, 230, DateTimeKind.Utc).AddTicks(6517),
                            Name = "Mare",
                            ProductSizeTypeId = new Guid("91fab09e-daf4-477c-b585-8621021a85f3"),
                            UpdatedOn = new DateTime(2024, 7, 7, 10, 34, 51, 230, DateTimeKind.Utc).AddTicks(6517)
                        },
                        new
                        {
                            Id = new Guid("3750e694-4a88-482f-b9cf-d1ce52c48460"),
                            CreatedOn = new DateTime(2024, 7, 7, 10, 34, 51, 230, DateTimeKind.Utc).AddTicks(6522),
                            Name = "Sportive",
                            ProductSizeTypeId = new Guid("91fab09e-daf4-477c-b585-8621021a85f3"),
                            UpdatedOn = new DateTime(2024, 7, 7, 10, 34, 51, 230, DateTimeKind.Utc).AddTicks(6522)
                        },
                        new
                        {
                            Id = new Guid("8fa8ed65-fd14-4aac-8db7-c58fbc193779"),
                            CreatedOn = new DateTime(2024, 7, 7, 10, 34, 51, 230, DateTimeKind.Utc).AddTicks(6525),
                            Name = "Cerimonia",
                            ProductSizeTypeId = new Guid("91fab09e-daf4-477c-b585-8621021a85f3"),
                            UpdatedOn = new DateTime(2024, 7, 7, 10, 34, 51, 230, DateTimeKind.Utc).AddTicks(6525)
                        });
                });

            modelBuilder.Entity("Troonch.Sales.Domain.Entities.ProductGender", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<DateTime>("UpdatedOn")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("ProductGenders");

                    b.HasData(
                        new
                        {
                            Id = new Guid("28f151a9-36c0-45a8-9256-a582a76ba057"),
                            CreatedOn = new DateTime(2024, 7, 7, 10, 34, 51, 230, DateTimeKind.Utc).AddTicks(5675),
                            Name = "Uomo",
                            UpdatedOn = new DateTime(2024, 7, 7, 10, 34, 51, 230, DateTimeKind.Utc).AddTicks(5679)
                        },
                        new
                        {
                            Id = new Guid("d1ea6acf-0d5b-4b25-bf4b-03906ad51565"),
                            CreatedOn = new DateTime(2024, 7, 7, 10, 34, 51, 230, DateTimeKind.Utc).AddTicks(5682),
                            Name = "Donna",
                            UpdatedOn = new DateTime(2024, 7, 7, 10, 34, 51, 230, DateTimeKind.Utc).AddTicks(5682)
                        },
                        new
                        {
                            Id = new Guid("7dafb481-82c5-460e-a436-dbbbb92cd226"),
                            CreatedOn = new DateTime(2024, 7, 7, 10, 34, 51, 230, DateTimeKind.Utc).AddTicks(5683),
                            Name = "Bambino",
                            UpdatedOn = new DateTime(2024, 7, 7, 10, 34, 51, 230, DateTimeKind.Utc).AddTicks(5683)
                        },
                        new
                        {
                            Id = new Guid("f65e9f97-bc3a-4e96-84d1-aa82e50a4fc5"),
                            CreatedOn = new DateTime(2024, 7, 7, 10, 34, 51, 230, DateTimeKind.Utc).AddTicks(5684),
                            Name = "Bambina",
                            UpdatedOn = new DateTime(2024, 7, 7, 10, 34, 51, 230, DateTimeKind.Utc).AddTicks(5685)
                        },
                        new
                        {
                            Id = new Guid("3b5cdea3-7de0-478b-94ac-21c327db0654"),
                            CreatedOn = new DateTime(2024, 7, 7, 10, 34, 51, 230, DateTimeKind.Utc).AddTicks(5686),
                            Name = "Neonato",
                            UpdatedOn = new DateTime(2024, 7, 7, 10, 34, 51, 230, DateTimeKind.Utc).AddTicks(5686)
                        });
                });

            modelBuilder.Entity("Troonch.Sales.Domain.Entities.ProductItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Barcode")
                        .HasMaxLength(30)
                        .IsUnicode(true)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("Color")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Currency")
                        .HasColumnType("int");

                    b.Property<decimal>("OriginalPrice")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<Guid>("ProductId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ProductSizeOptionId")
                        .HasColumnType("char(36)");

                    b.Property<int>("QuantityAvailable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<decimal>("SalePrice")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<DateTime>("UpdatedOn")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("Barcode")
                        .IsUnique();

                    b.HasIndex("ProductId");

                    b.HasIndex("ProductSizeOptionId");

                    b.ToTable("ProductItems");
                });

            modelBuilder.Entity("Troonch.Sales.Domain.Entities.ProductMaterial", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("UpdatedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.HasKey("Id");

                    b.ToTable("ProductMaterials");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f82bf43b-42ed-4fd4-ae3f-79bbdab4f7b2"),
                            CreatedOn = new DateTime(2024, 7, 7, 10, 34, 51, 230, DateTimeKind.Utc).AddTicks(5769),
                            UpdatedOn = new DateTime(2024, 7, 7, 10, 34, 51, 230, DateTimeKind.Utc).AddTicks(5769),
                            Value = "Cotone"
                        },
                        new
                        {
                            Id = new Guid("1a7a6ee4-2679-4891-9215-9639a53c22be"),
                            CreatedOn = new DateTime(2024, 7, 7, 10, 34, 51, 230, DateTimeKind.Utc).AddTicks(5772),
                            UpdatedOn = new DateTime(2024, 7, 7, 10, 34, 51, 230, DateTimeKind.Utc).AddTicks(5772),
                            Value = "Lana"
                        },
                        new
                        {
                            Id = new Guid("692c9046-c9b9-4efe-b555-5eddec9aeabf"),
                            CreatedOn = new DateTime(2024, 7, 7, 10, 34, 51, 230, DateTimeKind.Utc).AddTicks(5774),
                            UpdatedOn = new DateTime(2024, 7, 7, 10, 34, 51, 230, DateTimeKind.Utc).AddTicks(5774),
                            Value = "Seta"
                        },
                        new
                        {
                            Id = new Guid("a360bbdf-6632-4bd4-9e4c-c5c687a0b39e"),
                            CreatedOn = new DateTime(2024, 7, 7, 10, 34, 51, 230, DateTimeKind.Utc).AddTicks(5778),
                            UpdatedOn = new DateTime(2024, 7, 7, 10, 34, 51, 230, DateTimeKind.Utc).AddTicks(5779),
                            Value = "Lino"
                        },
                        new
                        {
                            Id = new Guid("309726b4-c4e4-44b9-85e5-38fe3182e28e"),
                            CreatedOn = new DateTime(2024, 7, 7, 10, 34, 51, 230, DateTimeKind.Utc).AddTicks(5780),
                            UpdatedOn = new DateTime(2024, 7, 7, 10, 34, 51, 230, DateTimeKind.Utc).AddTicks(5780),
                            Value = "Canapa"
                        },
                        new
                        {
                            Id = new Guid("fdf51d3c-b072-4e8f-abbb-4a37854cb9cc"),
                            CreatedOn = new DateTime(2024, 7, 7, 10, 34, 51, 230, DateTimeKind.Utc).AddTicks(5783),
                            UpdatedOn = new DateTime(2024, 7, 7, 10, 34, 51, 230, DateTimeKind.Utc).AddTicks(5784),
                            Value = "Bamboo"
                        });
                });

            modelBuilder.Entity("Troonch.Sales.Domain.Entities.ProductSizeOption", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("ProductSizeTypeId")
                        .HasColumnType("char(36)");

                    b.Property<int>("Sort")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("ProductSizeTypeId");

                    b.ToTable("ProductSizeOptions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("10bb7da3-0251-447c-a4ee-0d0bce2feacf"),
                            CreatedOn = new DateTime(2024, 7, 7, 10, 34, 51, 230, DateTimeKind.Utc).AddTicks(5902),
                            ProductSizeTypeId = new Guid("e9424a4f-c953-4a93-ba77-bfbe21ae43e7"),
                            Sort = 1,
                            UpdatedOn = new DateTime(2024, 7, 7, 10, 34, 51, 230, DateTimeKind.Utc).AddTicks(5902),
                            Value = "Taglia Unica"
                        },
                        new
                        {
                            Id = new Guid("c0523acb-d99d-45ca-893e-ff3bb91dba1a"),
                            CreatedOn = new DateTime(2024, 7, 7, 10, 34, 51, 230, DateTimeKind.Utc).AddTicks(5925),
                            ProductSizeTypeId = new Guid("30622354-36db-4221-9903-d3a633b25b26"),
                            Sort = 1,
                            UpdatedOn = new DateTime(2024, 7, 7, 10, 34, 51, 230, DateTimeKind.Utc).AddTicks(5926),
                            Value = "35"
                        },
                        new
                        {
                            Id = new Guid("8bd6175a-b5ab-4922-a91b-635314d6e49d"),
                            CreatedOn = new DateTime(2024, 7, 7, 10, 34, 51, 230, DateTimeKind.Utc).AddTicks(5930),
                            ProductSizeTypeId = new Guid("30622354-36db-4221-9903-d3a633b25b26"),
                            Sort = 2,
                            UpdatedOn = new DateTime(2024, 7, 7, 10, 34, 51, 230, DateTimeKind.Utc).AddTicks(5930),
                            Value = "36"
                        },
                        new
                        {
                            Id = new Guid("eb5f5cf5-9f1b-4ceb-bb0b-67d6c60a08f0"),
                            CreatedOn = new DateTime(2024, 7, 7, 10, 34, 51, 230, DateTimeKind.Utc).AddTicks(5934),
                            ProductSizeTypeId = new Guid("30622354-36db-4221-9903-d3a633b25b26"),
                            Sort = 3,
                            UpdatedOn = new DateTime(2024, 7, 7, 10, 34, 51, 230, DateTimeKind.Utc).AddTicks(5934),
                            Value = "37"
                        },
                        new
                        {
                            Id = new Guid("05ac0bf7-82d2-4872-b4f3-50870c49ea88"),
                            CreatedOn = new DateTime(2024, 7, 7, 10, 34, 51, 230, DateTimeKind.Utc).AddTicks(5938),
                            ProductSizeTypeId = new Guid("30622354-36db-4221-9903-d3a633b25b26"),
                            Sort = 4,
                            UpdatedOn = new DateTime(2024, 7, 7, 10, 34, 51, 230, DateTimeKind.Utc).AddTicks(5938),
                            Value = "38"
                        },
                        new
                        {
                            Id = new Guid("cb82432e-f4ac-4228-bc19-907bc426f5c5"),
                            CreatedOn = new DateTime(2024, 7, 7, 10, 34, 51, 230, DateTimeKind.Utc).AddTicks(5942),
                            ProductSizeTypeId = new Guid("30622354-36db-4221-9903-d3a633b25b26"),
                            Sort = 5,
                            UpdatedOn = new DateTime(2024, 7, 7, 10, 34, 51, 230, DateTimeKind.Utc).AddTicks(5943),
                            Value = "39"
                        },
                        new
                        {
                            Id = new Guid("bed10d28-7639-46ee-95ba-54106b97aab9"),
                            CreatedOn = new DateTime(2024, 7, 7, 10, 34, 51, 230, DateTimeKind.Utc).AddTicks(5946),
                            ProductSizeTypeId = new Guid("30622354-36db-4221-9903-d3a633b25b26"),
                            Sort = 6,
                            UpdatedOn = new DateTime(2024, 7, 7, 10, 34, 51, 230, DateTimeKind.Utc).AddTicks(5946),
                            Value = "40"
                        },
                        new
                        {
                            Id = new Guid("d5c7e284-4a7a-46b8-91ce-96e64a2a6ed4"),
                            CreatedOn = new DateTime(2024, 7, 7, 10, 34, 51, 230, DateTimeKind.Utc).AddTicks(5950),
                            ProductSizeTypeId = new Guid("30622354-36db-4221-9903-d3a633b25b26"),
                            Sort = 7,
                            UpdatedOn = new DateTime(2024, 7, 7, 10, 34, 51, 230, DateTimeKind.Utc).AddTicks(5950),
                            Value = "41"
                        },
                        new
                        {
                            Id = new Guid("ced1044c-8d4a-43ee-8981-114626c38345"),
                            CreatedOn = new DateTime(2024, 7, 7, 10, 34, 51, 230, DateTimeKind.Utc).AddTicks(5956),
                            ProductSizeTypeId = new Guid("30622354-36db-4221-9903-d3a633b25b26"),
                            Sort = 8,
                            UpdatedOn = new DateTime(2024, 7, 7, 10, 34, 51, 230, DateTimeKind.Utc).AddTicks(5956),
                            Value = "42"
                        },
                        new
                        {
                            Id = new Guid("1583a451-303d-44ba-895c-63bec8542922"),
                            CreatedOn = new DateTime(2024, 7, 7, 10, 34, 51, 230, DateTimeKind.Utc).AddTicks(5961),
                            ProductSizeTypeId = new Guid("30622354-36db-4221-9903-d3a633b25b26"),
                            Sort = 9,
                            UpdatedOn = new DateTime(2024, 7, 7, 10, 34, 51, 230, DateTimeKind.Utc).AddTicks(5961),
                            Value = "43"
                        },
                        new
                        {
                            Id = new Guid("36d1bc98-3448-4c70-8d2e-600a3fda3165"),
                            CreatedOn = new DateTime(2024, 7, 7, 10, 34, 51, 230, DateTimeKind.Utc).AddTicks(5965),
                            ProductSizeTypeId = new Guid("30622354-36db-4221-9903-d3a633b25b26"),
                            Sort = 10,
                            UpdatedOn = new DateTime(2024, 7, 7, 10, 34, 51, 230, DateTimeKind.Utc).AddTicks(5965),
                            Value = "44"
                        },
                        new
                        {
                            Id = new Guid("ffd4f18a-a208-4245-8359-957e53703c01"),
                            CreatedOn = new DateTime(2024, 7, 7, 10, 34, 51, 230, DateTimeKind.Utc).AddTicks(5969),
                            ProductSizeTypeId = new Guid("30622354-36db-4221-9903-d3a633b25b26"),
                            Sort = 11,
                            UpdatedOn = new DateTime(2024, 7, 7, 10, 34, 51, 230, DateTimeKind.Utc).AddTicks(5969),
                            Value = "45"
                        },
                        new
                        {
                            Id = new Guid("b5479996-be88-4653-9452-560d97418ea6"),
                            CreatedOn = new DateTime(2024, 7, 7, 10, 34, 51, 230, DateTimeKind.Utc).AddTicks(5972),
                            ProductSizeTypeId = new Guid("30622354-36db-4221-9903-d3a633b25b26"),
                            Sort = 12,
                            UpdatedOn = new DateTime(2024, 7, 7, 10, 34, 51, 230, DateTimeKind.Utc).AddTicks(5972),
                            Value = "46"
                        },
                        new
                        {
                            Id = new Guid("3e6fd2ec-527c-427f-8287-91d97915705f"),
                            CreatedOn = new DateTime(2024, 7, 7, 10, 34, 51, 230, DateTimeKind.Utc).AddTicks(5981),
                            ProductSizeTypeId = new Guid("91fab09e-daf4-477c-b585-8621021a85f3"),
                            Sort = 1,
                            UpdatedOn = new DateTime(2024, 7, 7, 10, 34, 51, 230, DateTimeKind.Utc).AddTicks(5981),
                            Value = "14"
                        },
                        new
                        {
                            Id = new Guid("3ab6c9bb-b4a8-416b-9c85-7ab6883f5531"),
                            CreatedOn = new DateTime(2024, 7, 7, 10, 34, 51, 230, DateTimeKind.Utc).AddTicks(5985),
                            ProductSizeTypeId = new Guid("91fab09e-daf4-477c-b585-8621021a85f3"),
                            Sort = 2,
                            UpdatedOn = new DateTime(2024, 7, 7, 10, 34, 51, 230, DateTimeKind.Utc).AddTicks(5985),
                            Value = "15"
                        },
                        new
                        {
                            Id = new Guid("cb1bdd43-1dde-4038-b976-b80c41be4643"),
                            CreatedOn = new DateTime(2024, 7, 7, 10, 34, 51, 230, DateTimeKind.Utc).AddTicks(5988),
                            ProductSizeTypeId = new Guid("91fab09e-daf4-477c-b585-8621021a85f3"),
                            Sort = 3,
                            UpdatedOn = new DateTime(2024, 7, 7, 10, 34, 51, 230, DateTimeKind.Utc).AddTicks(5988),
                            Value = "16"
                        },
                        new
                        {
                            Id = new Guid("1cfb6540-7c5c-4e3d-872e-e239418c4e8d"),
                            CreatedOn = new DateTime(2024, 7, 7, 10, 34, 51, 230, DateTimeKind.Utc).AddTicks(6014),
                            ProductSizeTypeId = new Guid("91fab09e-daf4-477c-b585-8621021a85f3"),
                            Sort = 4,
                            UpdatedOn = new DateTime(2024, 7, 7, 10, 34, 51, 230, DateTimeKind.Utc).AddTicks(6014),
                            Value = "17"
                        },
                        new
                        {
                            Id = new Guid("88fcf83d-7187-4d6d-b44b-56a911c12bce"),
                            CreatedOn = new DateTime(2024, 7, 7, 10, 34, 51, 230, DateTimeKind.Utc).AddTicks(6019),
                            ProductSizeTypeId = new Guid("91fab09e-daf4-477c-b585-8621021a85f3"),
                            Sort = 5,
                            UpdatedOn = new DateTime(2024, 7, 7, 10, 34, 51, 230, DateTimeKind.Utc).AddTicks(6019),
                            Value = "18"
                        },
                        new
                        {
                            Id = new Guid("b7e2359c-6c7b-444b-b534-deed2f95bc7a"),
                            CreatedOn = new DateTime(2024, 7, 7, 10, 34, 51, 230, DateTimeKind.Utc).AddTicks(6023),
                            ProductSizeTypeId = new Guid("91fab09e-daf4-477c-b585-8621021a85f3"),
                            Sort = 6,
                            UpdatedOn = new DateTime(2024, 7, 7, 10, 34, 51, 230, DateTimeKind.Utc).AddTicks(6023),
                            Value = "19"
                        },
                        new
                        {
                            Id = new Guid("ee0a70a0-376d-422e-a432-cae2f5a071d2"),
                            CreatedOn = new DateTime(2024, 7, 7, 10, 34, 51, 230, DateTimeKind.Utc).AddTicks(6026),
                            ProductSizeTypeId = new Guid("91fab09e-daf4-477c-b585-8621021a85f3"),
                            Sort = 7,
                            UpdatedOn = new DateTime(2024, 7, 7, 10, 34, 51, 230, DateTimeKind.Utc).AddTicks(6026),
                            Value = "20"
                        },
                        new
                        {
                            Id = new Guid("710f869d-0478-44f6-921e-0f8bff45ec45"),
                            CreatedOn = new DateTime(2024, 7, 7, 10, 34, 51, 230, DateTimeKind.Utc).AddTicks(6029),
                            ProductSizeTypeId = new Guid("91fab09e-daf4-477c-b585-8621021a85f3"),
                            Sort = 8,
                            UpdatedOn = new DateTime(2024, 7, 7, 10, 34, 51, 230, DateTimeKind.Utc).AddTicks(6029),
                            Value = "21"
                        },
                        new
                        {
                            Id = new Guid("4b9bf4ff-a015-472a-8d07-055de14631ea"),
                            CreatedOn = new DateTime(2024, 7, 7, 10, 34, 51, 230, DateTimeKind.Utc).AddTicks(6031),
                            ProductSizeTypeId = new Guid("91fab09e-daf4-477c-b585-8621021a85f3"),
                            Sort = 9,
                            UpdatedOn = new DateTime(2024, 7, 7, 10, 34, 51, 230, DateTimeKind.Utc).AddTicks(6032),
                            Value = "22"
                        },
                        new
                        {
                            Id = new Guid("91e72335-942c-4e79-8576-991d08321f3f"),
                            CreatedOn = new DateTime(2024, 7, 7, 10, 34, 51, 230, DateTimeKind.Utc).AddTicks(6034),
                            ProductSizeTypeId = new Guid("91fab09e-daf4-477c-b585-8621021a85f3"),
                            Sort = 10,
                            UpdatedOn = new DateTime(2024, 7, 7, 10, 34, 51, 230, DateTimeKind.Utc).AddTicks(6035),
                            Value = "23"
                        },
                        new
                        {
                            Id = new Guid("fd57a2ff-d49d-4de4-a05e-7d24afef7ae9"),
                            CreatedOn = new DateTime(2024, 7, 7, 10, 34, 51, 230, DateTimeKind.Utc).AddTicks(6038),
                            ProductSizeTypeId = new Guid("91fab09e-daf4-477c-b585-8621021a85f3"),
                            Sort = 11,
                            UpdatedOn = new DateTime(2024, 7, 7, 10, 34, 51, 230, DateTimeKind.Utc).AddTicks(6039),
                            Value = "24"
                        },
                        new
                        {
                            Id = new Guid("5d0fa23e-c770-45e7-b33b-37861cce2e72"),
                            CreatedOn = new DateTime(2024, 7, 7, 10, 34, 51, 230, DateTimeKind.Utc).AddTicks(6043),
                            ProductSizeTypeId = new Guid("91fab09e-daf4-477c-b585-8621021a85f3"),
                            Sort = 12,
                            UpdatedOn = new DateTime(2024, 7, 7, 10, 34, 51, 230, DateTimeKind.Utc).AddTicks(6043),
                            Value = "25"
                        },
                        new
                        {
                            Id = new Guid("f5884774-87f9-4e72-ab46-9a3b370507e4"),
                            CreatedOn = new DateTime(2024, 7, 7, 10, 34, 51, 230, DateTimeKind.Utc).AddTicks(6046),
                            ProductSizeTypeId = new Guid("91fab09e-daf4-477c-b585-8621021a85f3"),
                            Sort = 13,
                            UpdatedOn = new DateTime(2024, 7, 7, 10, 34, 51, 230, DateTimeKind.Utc).AddTicks(6046),
                            Value = "26"
                        },
                        new
                        {
                            Id = new Guid("b611d421-098c-4bac-8d9a-5d3027e4f608"),
                            CreatedOn = new DateTime(2024, 7, 7, 10, 34, 51, 230, DateTimeKind.Utc).AddTicks(6049),
                            ProductSizeTypeId = new Guid("91fab09e-daf4-477c-b585-8621021a85f3"),
                            Sort = 14,
                            UpdatedOn = new DateTime(2024, 7, 7, 10, 34, 51, 230, DateTimeKind.Utc).AddTicks(6049),
                            Value = "27"
                        },
                        new
                        {
                            Id = new Guid("dbb46671-45bb-43ab-893d-5d28251db30c"),
                            CreatedOn = new DateTime(2024, 7, 7, 10, 34, 51, 230, DateTimeKind.Utc).AddTicks(6052),
                            ProductSizeTypeId = new Guid("91fab09e-daf4-477c-b585-8621021a85f3"),
                            Sort = 15,
                            UpdatedOn = new DateTime(2024, 7, 7, 10, 34, 51, 230, DateTimeKind.Utc).AddTicks(6052),
                            Value = "28"
                        },
                        new
                        {
                            Id = new Guid("432c79a2-aba1-4e0d-947a-b8f7eaafe7a4"),
                            CreatedOn = new DateTime(2024, 7, 7, 10, 34, 51, 230, DateTimeKind.Utc).AddTicks(6055),
                            ProductSizeTypeId = new Guid("91fab09e-daf4-477c-b585-8621021a85f3"),
                            Sort = 16,
                            UpdatedOn = new DateTime(2024, 7, 7, 10, 34, 51, 230, DateTimeKind.Utc).AddTicks(6055),
                            Value = "29"
                        },
                        new
                        {
                            Id = new Guid("3ae5e2f5-b7c7-42e4-a656-21f9cd95dafd"),
                            CreatedOn = new DateTime(2024, 7, 7, 10, 34, 51, 230, DateTimeKind.Utc).AddTicks(6058),
                            ProductSizeTypeId = new Guid("91fab09e-daf4-477c-b585-8621021a85f3"),
                            Sort = 17,
                            UpdatedOn = new DateTime(2024, 7, 7, 10, 34, 51, 230, DateTimeKind.Utc).AddTicks(6058),
                            Value = "30"
                        },
                        new
                        {
                            Id = new Guid("53bbe74c-47e3-4ac1-96eb-4c020a9fed7b"),
                            CreatedOn = new DateTime(2024, 7, 7, 10, 34, 51, 230, DateTimeKind.Utc).AddTicks(6061),
                            ProductSizeTypeId = new Guid("91fab09e-daf4-477c-b585-8621021a85f3"),
                            Sort = 18,
                            UpdatedOn = new DateTime(2024, 7, 7, 10, 34, 51, 230, DateTimeKind.Utc).AddTicks(6061),
                            Value = "31"
                        },
                        new
                        {
                            Id = new Guid("0ee41eb2-172f-4202-942e-c25b62d9fd53"),
                            CreatedOn = new DateTime(2024, 7, 7, 10, 34, 51, 230, DateTimeKind.Utc).AddTicks(6064),
                            ProductSizeTypeId = new Guid("91fab09e-daf4-477c-b585-8621021a85f3"),
                            Sort = 19,
                            UpdatedOn = new DateTime(2024, 7, 7, 10, 34, 51, 230, DateTimeKind.Utc).AddTicks(6064),
                            Value = "32"
                        },
                        new
                        {
                            Id = new Guid("435780d2-4638-42cd-be8c-974e042c8e13"),
                            CreatedOn = new DateTime(2024, 7, 7, 10, 34, 51, 230, DateTimeKind.Utc).AddTicks(6069),
                            ProductSizeTypeId = new Guid("91fab09e-daf4-477c-b585-8621021a85f3"),
                            Sort = 20,
                            UpdatedOn = new DateTime(2024, 7, 7, 10, 34, 51, 230, DateTimeKind.Utc).AddTicks(6069),
                            Value = "33"
                        },
                        new
                        {
                            Id = new Guid("11bc1389-570c-439a-a342-c2dac8f8971b"),
                            CreatedOn = new DateTime(2024, 7, 7, 10, 34, 51, 230, DateTimeKind.Utc).AddTicks(6073),
                            ProductSizeTypeId = new Guid("91fab09e-daf4-477c-b585-8621021a85f3"),
                            Sort = 21,
                            UpdatedOn = new DateTime(2024, 7, 7, 10, 34, 51, 230, DateTimeKind.Utc).AddTicks(6073),
                            Value = "34"
                        },
                        new
                        {
                            Id = new Guid("fb693e76-56d0-4e25-8120-69dd444ffe21"),
                            CreatedOn = new DateTime(2024, 7, 7, 10, 34, 51, 230, DateTimeKind.Utc).AddTicks(6084),
                            ProductSizeTypeId = new Guid("9fe00ea4-831a-4044-b45b-556c81017fff"),
                            Sort = 1,
                            UpdatedOn = new DateTime(2024, 7, 7, 10, 34, 51, 230, DateTimeKind.Utc).AddTicks(6085),
                            Value = "XXS"
                        },
                        new
                        {
                            Id = new Guid("3eceeef6-9b55-47ce-aed1-af597e6e267e"),
                            CreatedOn = new DateTime(2024, 7, 7, 10, 34, 51, 230, DateTimeKind.Utc).AddTicks(6088),
                            ProductSizeTypeId = new Guid("9fe00ea4-831a-4044-b45b-556c81017fff"),
                            Sort = 2,
                            UpdatedOn = new DateTime(2024, 7, 7, 10, 34, 51, 230, DateTimeKind.Utc).AddTicks(6088),
                            Value = "XS"
                        },
                        new
                        {
                            Id = new Guid("3906c06f-add5-4e55-a64a-4085f4d83e99"),
                            CreatedOn = new DateTime(2024, 7, 7, 10, 34, 51, 230, DateTimeKind.Utc).AddTicks(6090),
                            ProductSizeTypeId = new Guid("9fe00ea4-831a-4044-b45b-556c81017fff"),
                            Sort = 3,
                            UpdatedOn = new DateTime(2024, 7, 7, 10, 34, 51, 230, DateTimeKind.Utc).AddTicks(6091),
                            Value = "S"
                        },
                        new
                        {
                            Id = new Guid("2a746f95-6ba0-47e9-8c51-fe8988cea2a5"),
                            CreatedOn = new DateTime(2024, 7, 7, 10, 34, 51, 230, DateTimeKind.Utc).AddTicks(6093),
                            ProductSizeTypeId = new Guid("9fe00ea4-831a-4044-b45b-556c81017fff"),
                            Sort = 4,
                            UpdatedOn = new DateTime(2024, 7, 7, 10, 34, 51, 230, DateTimeKind.Utc).AddTicks(6093),
                            Value = "M"
                        },
                        new
                        {
                            Id = new Guid("3233fafb-0ce6-4319-a7dd-2e60276ed86d"),
                            CreatedOn = new DateTime(2024, 7, 7, 10, 34, 51, 230, DateTimeKind.Utc).AddTicks(6096),
                            ProductSizeTypeId = new Guid("9fe00ea4-831a-4044-b45b-556c81017fff"),
                            Sort = 5,
                            UpdatedOn = new DateTime(2024, 7, 7, 10, 34, 51, 230, DateTimeKind.Utc).AddTicks(6096),
                            Value = "L"
                        },
                        new
                        {
                            Id = new Guid("637938b4-87b2-48c1-b8c7-686b7d5011d6"),
                            CreatedOn = new DateTime(2024, 7, 7, 10, 34, 51, 230, DateTimeKind.Utc).AddTicks(6098),
                            ProductSizeTypeId = new Guid("9fe00ea4-831a-4044-b45b-556c81017fff"),
                            Sort = 6,
                            UpdatedOn = new DateTime(2024, 7, 7, 10, 34, 51, 230, DateTimeKind.Utc).AddTicks(6099),
                            Value = "XL"
                        },
                        new
                        {
                            Id = new Guid("28b71614-541b-4f12-9fe6-2f0b5a060166"),
                            CreatedOn = new DateTime(2024, 7, 7, 10, 34, 51, 230, DateTimeKind.Utc).AddTicks(6103),
                            ProductSizeTypeId = new Guid("9fe00ea4-831a-4044-b45b-556c81017fff"),
                            Sort = 7,
                            UpdatedOn = new DateTime(2024, 7, 7, 10, 34, 51, 230, DateTimeKind.Utc).AddTicks(6103),
                            Value = "XXL"
                        },
                        new
                        {
                            Id = new Guid("847429c0-c5b6-40b1-968c-bc8ae6438917"),
                            CreatedOn = new DateTime(2024, 7, 7, 10, 34, 51, 230, DateTimeKind.Utc).AddTicks(6106),
                            ProductSizeTypeId = new Guid("9fe00ea4-831a-4044-b45b-556c81017fff"),
                            Sort = 8,
                            UpdatedOn = new DateTime(2024, 7, 7, 10, 34, 51, 230, DateTimeKind.Utc).AddTicks(6106),
                            Value = "XXXL"
                        },
                        new
                        {
                            Id = new Guid("c785f10d-ef99-4ab1-b85f-aef5466efff8"),
                            CreatedOn = new DateTime(2024, 7, 7, 10, 34, 51, 230, DateTimeKind.Utc).AddTicks(6118),
                            ProductSizeTypeId = new Guid("b6829a28-318b-46ff-a059-d6f91743f92c"),
                            Sort = 1,
                            UpdatedOn = new DateTime(2024, 7, 7, 10, 34, 51, 230, DateTimeKind.Utc).AddTicks(6119),
                            Value = "4M"
                        },
                        new
                        {
                            Id = new Guid("546bc6c2-499a-4a9c-8364-a97e9ff839cf"),
                            CreatedOn = new DateTime(2024, 7, 7, 10, 34, 51, 230, DateTimeKind.Utc).AddTicks(6122),
                            ProductSizeTypeId = new Guid("b6829a28-318b-46ff-a059-d6f91743f92c"),
                            Sort = 2,
                            UpdatedOn = new DateTime(2024, 7, 7, 10, 34, 51, 230, DateTimeKind.Utc).AddTicks(6122),
                            Value = "5M"
                        },
                        new
                        {
                            Id = new Guid("a7958864-e7ed-4028-86c1-fa054efff765"),
                            CreatedOn = new DateTime(2024, 7, 7, 10, 34, 51, 230, DateTimeKind.Utc).AddTicks(6124),
                            ProductSizeTypeId = new Guid("b6829a28-318b-46ff-a059-d6f91743f92c"),
                            Sort = 3,
                            UpdatedOn = new DateTime(2024, 7, 7, 10, 34, 51, 230, DateTimeKind.Utc).AddTicks(6125),
                            Value = "6M"
                        },
                        new
                        {
                            Id = new Guid("93d695b8-b159-4814-b14a-2ef5b0f81ae2"),
                            CreatedOn = new DateTime(2024, 7, 7, 10, 34, 51, 230, DateTimeKind.Utc).AddTicks(6127),
                            ProductSizeTypeId = new Guid("b6829a28-318b-46ff-a059-d6f91743f92c"),
                            Sort = 4,
                            UpdatedOn = new DateTime(2024, 7, 7, 10, 34, 51, 230, DateTimeKind.Utc).AddTicks(6127),
                            Value = "7M"
                        },
                        new
                        {
                            Id = new Guid("f747f60a-332a-40a9-adc2-d7bc561ab0ca"),
                            CreatedOn = new DateTime(2024, 7, 7, 10, 34, 51, 230, DateTimeKind.Utc).AddTicks(6129),
                            ProductSizeTypeId = new Guid("b6829a28-318b-46ff-a059-d6f91743f92c"),
                            Sort = 5,
                            UpdatedOn = new DateTime(2024, 7, 7, 10, 34, 51, 230, DateTimeKind.Utc).AddTicks(6129),
                            Value = "8M"
                        },
                        new
                        {
                            Id = new Guid("ed386f36-afd7-4822-a902-aa633cd79a4c"),
                            CreatedOn = new DateTime(2024, 7, 7, 10, 34, 51, 230, DateTimeKind.Utc).AddTicks(6132),
                            ProductSizeTypeId = new Guid("b6829a28-318b-46ff-a059-d6f91743f92c"),
                            Sort = 6,
                            UpdatedOn = new DateTime(2024, 7, 7, 10, 34, 51, 230, DateTimeKind.Utc).AddTicks(6132),
                            Value = "10M"
                        },
                        new
                        {
                            Id = new Guid("59fe5558-31ce-4f4b-bd37-1e29fa505ca4"),
                            CreatedOn = new DateTime(2024, 7, 7, 10, 34, 51, 230, DateTimeKind.Utc).AddTicks(6136),
                            ProductSizeTypeId = new Guid("b6829a28-318b-46ff-a059-d6f91743f92c"),
                            Sort = 7,
                            UpdatedOn = new DateTime(2024, 7, 7, 10, 34, 51, 230, DateTimeKind.Utc).AddTicks(6136),
                            Value = "12M"
                        },
                        new
                        {
                            Id = new Guid("b5cc9ac6-c4ee-4b03-bd99-e955aa0adf52"),
                            CreatedOn = new DateTime(2024, 7, 7, 10, 34, 51, 230, DateTimeKind.Utc).AddTicks(6156),
                            ProductSizeTypeId = new Guid("b6829a28-318b-46ff-a059-d6f91743f92c"),
                            Sort = 8,
                            UpdatedOn = new DateTime(2024, 7, 7, 10, 34, 51, 230, DateTimeKind.Utc).AddTicks(6157),
                            Value = "16M"
                        },
                        new
                        {
                            Id = new Guid("10a8a0b4-de2c-4102-89b8-7301251eb5b9"),
                            CreatedOn = new DateTime(2024, 7, 7, 10, 34, 51, 230, DateTimeKind.Utc).AddTicks(6159),
                            ProductSizeTypeId = new Guid("b6829a28-318b-46ff-a059-d6f91743f92c"),
                            Sort = 9,
                            UpdatedOn = new DateTime(2024, 7, 7, 10, 34, 51, 230, DateTimeKind.Utc).AddTicks(6159),
                            Value = "24M"
                        },
                        new
                        {
                            Id = new Guid("9fbed59f-ec7a-47b9-9bb6-1e11c92b9021"),
                            CreatedOn = new DateTime(2024, 7, 7, 10, 34, 51, 230, DateTimeKind.Utc).AddTicks(6162),
                            ProductSizeTypeId = new Guid("b6829a28-318b-46ff-a059-d6f91743f92c"),
                            Sort = 10,
                            UpdatedOn = new DateTime(2024, 7, 7, 10, 34, 51, 230, DateTimeKind.Utc).AddTicks(6162),
                            Value = "3Y/A"
                        },
                        new
                        {
                            Id = new Guid("48d87eb4-66fc-4f69-9d91-90866b4878ef"),
                            CreatedOn = new DateTime(2024, 7, 7, 10, 34, 51, 230, DateTimeKind.Utc).AddTicks(6165),
                            ProductSizeTypeId = new Guid("b6829a28-318b-46ff-a059-d6f91743f92c"),
                            Sort = 11,
                            UpdatedOn = new DateTime(2024, 7, 7, 10, 34, 51, 230, DateTimeKind.Utc).AddTicks(6165),
                            Value = "4Y/A"
                        },
                        new
                        {
                            Id = new Guid("4de9d124-4c5e-45d8-9edc-e4b301c9f822"),
                            CreatedOn = new DateTime(2024, 7, 7, 10, 34, 51, 230, DateTimeKind.Utc).AddTicks(6167),
                            ProductSizeTypeId = new Guid("b6829a28-318b-46ff-a059-d6f91743f92c"),
                            Sort = 12,
                            UpdatedOn = new DateTime(2024, 7, 7, 10, 34, 51, 230, DateTimeKind.Utc).AddTicks(6167),
                            Value = "5Y/A"
                        },
                        new
                        {
                            Id = new Guid("3c187a23-ba5c-471f-bfe6-92f8e00b56f3"),
                            CreatedOn = new DateTime(2024, 7, 7, 10, 34, 51, 230, DateTimeKind.Utc).AddTicks(6170),
                            ProductSizeTypeId = new Guid("b6829a28-318b-46ff-a059-d6f91743f92c"),
                            Sort = 13,
                            UpdatedOn = new DateTime(2024, 7, 7, 10, 34, 51, 230, DateTimeKind.Utc).AddTicks(6170),
                            Value = "6Y/A"
                        },
                        new
                        {
                            Id = new Guid("8c475d22-07d7-44f6-9659-29d77a31b58d"),
                            CreatedOn = new DateTime(2024, 7, 7, 10, 34, 51, 230, DateTimeKind.Utc).AddTicks(6172),
                            ProductSizeTypeId = new Guid("b6829a28-318b-46ff-a059-d6f91743f92c"),
                            Sort = 14,
                            UpdatedOn = new DateTime(2024, 7, 7, 10, 34, 51, 230, DateTimeKind.Utc).AddTicks(6172),
                            Value = "7Y/A"
                        },
                        new
                        {
                            Id = new Guid("3abcf5bb-3582-4336-840e-948ef1fb768f"),
                            CreatedOn = new DateTime(2024, 7, 7, 10, 34, 51, 230, DateTimeKind.Utc).AddTicks(6176),
                            ProductSizeTypeId = new Guid("b6829a28-318b-46ff-a059-d6f91743f92c"),
                            Sort = 15,
                            UpdatedOn = new DateTime(2024, 7, 7, 10, 34, 51, 230, DateTimeKind.Utc).AddTicks(6176),
                            Value = "8Y/A"
                        },
                        new
                        {
                            Id = new Guid("51976a5b-294a-4e01-b82c-1472df1f61bf"),
                            CreatedOn = new DateTime(2024, 7, 7, 10, 34, 51, 230, DateTimeKind.Utc).AddTicks(6179),
                            ProductSizeTypeId = new Guid("b6829a28-318b-46ff-a059-d6f91743f92c"),
                            Sort = 16,
                            UpdatedOn = new DateTime(2024, 7, 7, 10, 34, 51, 230, DateTimeKind.Utc).AddTicks(6179),
                            Value = "9Y/A"
                        },
                        new
                        {
                            Id = new Guid("acb75a1e-2f2c-4dd8-a06f-489bfb771205"),
                            CreatedOn = new DateTime(2024, 7, 7, 10, 34, 51, 230, DateTimeKind.Utc).AddTicks(6181),
                            ProductSizeTypeId = new Guid("b6829a28-318b-46ff-a059-d6f91743f92c"),
                            Sort = 17,
                            UpdatedOn = new DateTime(2024, 7, 7, 10, 34, 51, 230, DateTimeKind.Utc).AddTicks(6181),
                            Value = "10Y/A"
                        },
                        new
                        {
                            Id = new Guid("913cd9cc-ac68-4709-ae5b-ac51334d09a8"),
                            CreatedOn = new DateTime(2024, 7, 7, 10, 34, 51, 230, DateTimeKind.Utc).AddTicks(6184),
                            ProductSizeTypeId = new Guid("b6829a28-318b-46ff-a059-d6f91743f92c"),
                            Sort = 18,
                            UpdatedOn = new DateTime(2024, 7, 7, 10, 34, 51, 230, DateTimeKind.Utc).AddTicks(6184),
                            Value = "11Y/A"
                        },
                        new
                        {
                            Id = new Guid("d73b277b-22ec-4b30-9d64-6a891ca5509e"),
                            CreatedOn = new DateTime(2024, 7, 7, 10, 34, 51, 230, DateTimeKind.Utc).AddTicks(6186),
                            ProductSizeTypeId = new Guid("b6829a28-318b-46ff-a059-d6f91743f92c"),
                            Sort = 19,
                            UpdatedOn = new DateTime(2024, 7, 7, 10, 34, 51, 230, DateTimeKind.Utc).AddTicks(6186),
                            Value = "12Y/A"
                        },
                        new
                        {
                            Id = new Guid("ad79f158-8db8-4aac-b17a-c70e6b684adb"),
                            CreatedOn = new DateTime(2024, 7, 7, 10, 34, 51, 230, DateTimeKind.Utc).AddTicks(6189),
                            ProductSizeTypeId = new Guid("b6829a28-318b-46ff-a059-d6f91743f92c"),
                            Sort = 20,
                            UpdatedOn = new DateTime(2024, 7, 7, 10, 34, 51, 230, DateTimeKind.Utc).AddTicks(6189),
                            Value = "13Y/A"
                        },
                        new
                        {
                            Id = new Guid("5a11cc7c-8a7e-488a-9ca5-6d9b253d0080"),
                            CreatedOn = new DateTime(2024, 7, 7, 10, 34, 51, 230, DateTimeKind.Utc).AddTicks(6191),
                            ProductSizeTypeId = new Guid("b6829a28-318b-46ff-a059-d6f91743f92c"),
                            Sort = 21,
                            UpdatedOn = new DateTime(2024, 7, 7, 10, 34, 51, 230, DateTimeKind.Utc).AddTicks(6191),
                            Value = "14Y/A"
                        },
                        new
                        {
                            Id = new Guid("28169b5e-3fee-4af0-8cc1-1a4d2fb5faf1"),
                            CreatedOn = new DateTime(2024, 7, 7, 10, 34, 51, 230, DateTimeKind.Utc).AddTicks(6194),
                            ProductSizeTypeId = new Guid("b6829a28-318b-46ff-a059-d6f91743f92c"),
                            Sort = 22,
                            UpdatedOn = new DateTime(2024, 7, 7, 10, 34, 51, 230, DateTimeKind.Utc).AddTicks(6194),
                            Value = "15Y/A"
                        },
                        new
                        {
                            Id = new Guid("52ad1ac7-5dd2-4bfc-8317-729258f616e4"),
                            CreatedOn = new DateTime(2024, 7, 7, 10, 34, 51, 230, DateTimeKind.Utc).AddTicks(6198),
                            ProductSizeTypeId = new Guid("b6829a28-318b-46ff-a059-d6f91743f92c"),
                            Sort = 23,
                            UpdatedOn = new DateTime(2024, 7, 7, 10, 34, 51, 230, DateTimeKind.Utc).AddTicks(6198),
                            Value = "16Y/A"
                        });
                });

            modelBuilder.Entity("Troonch.Sales.Domain.Entities.ProductSizeType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<DateTime>("UpdatedOn")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("ProductSizeTypes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b6829a28-318b-46ff-a059-d6f91743f92c"),
                            CreatedOn = new DateTime(2024, 7, 7, 10, 34, 51, 230, DateTimeKind.Utc).AddTicks(5827),
                            Name = "Abiti - Completi - Vestiti - Bambino/a",
                            UpdatedOn = new DateTime(2024, 7, 7, 10, 34, 51, 230, DateTimeKind.Utc).AddTicks(5827)
                        },
                        new
                        {
                            Id = new Guid("9fe00ea4-831a-4044-b45b-556c81017fff"),
                            CreatedOn = new DateTime(2024, 7, 7, 10, 34, 51, 230, DateTimeKind.Utc).AddTicks(5830),
                            Name = "Abiti - Vestiti - Uomo/Donna",
                            UpdatedOn = new DateTime(2024, 7, 7, 10, 34, 51, 230, DateTimeKind.Utc).AddTicks(5830)
                        },
                        new
                        {
                            Id = new Guid("e9424a4f-c953-4a93-ba77-bfbe21ae43e7"),
                            CreatedOn = new DateTime(2024, 7, 7, 10, 34, 51, 230, DateTimeKind.Utc).AddTicks(5832),
                            Name = "Accessori",
                            UpdatedOn = new DateTime(2024, 7, 7, 10, 34, 51, 230, DateTimeKind.Utc).AddTicks(5832)
                        },
                        new
                        {
                            Id = new Guid("91fab09e-daf4-477c-b585-8621021a85f3"),
                            CreatedOn = new DateTime(2024, 7, 7, 10, 34, 51, 230, DateTimeKind.Utc).AddTicks(5833),
                            Name = "Scarpe Bambino/a",
                            UpdatedOn = new DateTime(2024, 7, 7, 10, 34, 51, 230, DateTimeKind.Utc).AddTicks(5833)
                        },
                        new
                        {
                            Id = new Guid("30622354-36db-4221-9903-d3a633b25b26"),
                            CreatedOn = new DateTime(2024, 7, 7, 10, 34, 51, 230, DateTimeKind.Utc).AddTicks(5835),
                            Name = "Scarpe Uomo/Donna",
                            UpdatedOn = new DateTime(2024, 7, 7, 10, 34, 51, 230, DateTimeKind.Utc).AddTicks(5835)
                        });
                });

            modelBuilder.Entity("Troonch.Sales.Domain.Entities.ProductTag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("UpdatedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("ProductTag");
                });

            modelBuilder.Entity("Troonch.Sales.Domain.Entities.ProductTagLookup", b =>
                {
                    b.Property<Guid>("ProductId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("TagId")
                        .HasColumnType("char(36)");

                    b.HasKey("ProductId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("ProductTagLookup");
                });

            modelBuilder.Entity("Troonch.Sales.Domain.Entities.Product", b =>
                {
                    b.HasOne("Troonch.Sales.Domain.Entities.ProductBrand", "ProductBrand")
                        .WithMany("Products")
                        .HasForeignKey("ProductBrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Troonch.Sales.Domain.Entities.ProductCategory", "ProductCategory")
                        .WithMany("Products")
                        .HasForeignKey("ProductCategoryId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Troonch.Sales.Domain.Entities.ProductGender", "ProductGender")
                        .WithMany("Products")
                        .HasForeignKey("ProductGenderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Troonch.Sales.Domain.Entities.ProductMaterial", "ProductMaterial")
                        .WithMany("Products")
                        .HasForeignKey("ProductMaterialId");

                    b.Navigation("ProductBrand");

                    b.Navigation("ProductCategory");

                    b.Navigation("ProductGender");

                    b.Navigation("ProductMaterial");
                });

            modelBuilder.Entity("Troonch.Sales.Domain.Entities.ProductCategory", b =>
                {
                    b.HasOne("Troonch.Sales.Domain.Entities.ProductSizeType", "ProductSizeType")
                        .WithMany("ProductCategories")
                        .HasForeignKey("ProductSizeTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductSizeType");
                });

            modelBuilder.Entity("Troonch.Sales.Domain.Entities.ProductItem", b =>
                {
                    b.HasOne("Troonch.Sales.Domain.Entities.Product", "Product")
                        .WithMany("ProductItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Troonch.Sales.Domain.Entities.ProductSizeOption", "ProductSizeOption")
                        .WithMany("ProductItems")
                        .HasForeignKey("ProductSizeOptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("ProductSizeOption");
                });

            modelBuilder.Entity("Troonch.Sales.Domain.Entities.ProductSizeOption", b =>
                {
                    b.HasOne("Troonch.Sales.Domain.Entities.ProductSizeType", "ProductSizeType")
                        .WithMany("ProductSizeOptions")
                        .HasForeignKey("ProductSizeTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductSizeType");
                });

            modelBuilder.Entity("Troonch.Sales.Domain.Entities.ProductTagLookup", b =>
                {
                    b.HasOne("Troonch.Sales.Domain.Entities.Product", "Product")
                        .WithMany("ProductTags")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Troonch.Sales.Domain.Entities.ProductTag", "ProductTag")
                        .WithMany("ProductTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("ProductTag");
                });

            modelBuilder.Entity("Troonch.Sales.Domain.Entities.Product", b =>
                {
                    b.Navigation("ProductItems");

                    b.Navigation("ProductTags");
                });

            modelBuilder.Entity("Troonch.Sales.Domain.Entities.ProductBrand", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("Troonch.Sales.Domain.Entities.ProductCategory", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("Troonch.Sales.Domain.Entities.ProductGender", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("Troonch.Sales.Domain.Entities.ProductMaterial", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("Troonch.Sales.Domain.Entities.ProductSizeOption", b =>
                {
                    b.Navigation("ProductItems");
                });

            modelBuilder.Entity("Troonch.Sales.Domain.Entities.ProductSizeType", b =>
                {
                    b.Navigation("ProductCategories");

                    b.Navigation("ProductSizeOptions");
                });

            modelBuilder.Entity("Troonch.Sales.Domain.Entities.ProductTag", b =>
                {
                    b.Navigation("ProductTags");
                });
#pragma warning restore 612, 618
        }
    }
}
