// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Troonch.Sales.DataAccess;

#nullable disable

namespace Troonch.RetailSales.Product.DataAccess.Migrations
{
    [DbContext(typeof(RetailSalesProductDataContext))]
    partial class RetailSalesProductDataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Troonch.Sales.Domain.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("CoverImageLink")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsPublished")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<Guid>("ProductBrandId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ProductCategoryId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ProductGenderId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("ProductMaterialId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("UpdatedOn")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("CoverImageLink")
                        .IsUnique();

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("ProductBrandId");

                    b.HasIndex("ProductCategoryId");

                    b.HasIndex("ProductGenderId");

                    b.HasIndex("ProductMaterialId");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Products");
                });

            modelBuilder.Entity("Troonch.Sales.Domain.Entities.ProductBrand", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(128)
                        .IsUnicode(true)
                        .HasColumnType("varchar(128)");

                    b.Property<DateTime>("UpdatedOn")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("ProductBrands");
                });

            modelBuilder.Entity("Troonch.Sales.Domain.Entities.ProductCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<Guid>("ProductSizeTypeId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("UpdatedOn")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.HasIndex("ProductSizeTypeId");

                    b.ToTable("ProductCategories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d5ff2956-a012-4418-a5b0-497cf18d884d"),
                            CreatedOn = new DateTime(2024, 7, 10, 6, 32, 7, 135, DateTimeKind.Utc).AddTicks(9363),
                            Name = "Abiti - Completi",
                            ProductSizeTypeId = new Guid("b9c10a10-806c-4db3-94ac-87a9b5657442"),
                            UpdatedOn = new DateTime(2024, 7, 10, 6, 32, 7, 135, DateTimeKind.Utc).AddTicks(9364)
                        },
                        new
                        {
                            Id = new Guid("9e95bcfa-424c-4db1-b3e1-39ab3b891fef"),
                            CreatedOn = new DateTime(2024, 7, 10, 6, 32, 7, 135, DateTimeKind.Utc).AddTicks(9367),
                            Name = "Giubbino",
                            ProductSizeTypeId = new Guid("b9c10a10-806c-4db3-94ac-87a9b5657442"),
                            UpdatedOn = new DateTime(2024, 7, 10, 6, 32, 7, 135, DateTimeKind.Utc).AddTicks(9367)
                        },
                        new
                        {
                            Id = new Guid("8479ca3c-3223-404a-bba9-7607d697c507"),
                            CreatedOn = new DateTime(2024, 7, 10, 6, 32, 7, 135, DateTimeKind.Utc).AddTicks(9370),
                            Name = "Felpa",
                            ProductSizeTypeId = new Guid("b9c10a10-806c-4db3-94ac-87a9b5657442"),
                            UpdatedOn = new DateTime(2024, 7, 10, 6, 32, 7, 135, DateTimeKind.Utc).AddTicks(9370)
                        },
                        new
                        {
                            Id = new Guid("13cb2e71-3e9f-4a2d-b3e3-ade4179535cc"),
                            CreatedOn = new DateTime(2024, 7, 10, 6, 32, 7, 135, DateTimeKind.Utc).AddTicks(9372),
                            Name = "Jeans",
                            ProductSizeTypeId = new Guid("b9c10a10-806c-4db3-94ac-87a9b5657442"),
                            UpdatedOn = new DateTime(2024, 7, 10, 6, 32, 7, 135, DateTimeKind.Utc).AddTicks(9373)
                        },
                        new
                        {
                            Id = new Guid("c4632faa-88d6-4f9b-ae1e-ed1c4226e676"),
                            CreatedOn = new DateTime(2024, 7, 10, 6, 32, 7, 135, DateTimeKind.Utc).AddTicks(9375),
                            Name = "Cardigan",
                            ProductSizeTypeId = new Guid("b9c10a10-806c-4db3-94ac-87a9b5657442"),
                            UpdatedOn = new DateTime(2024, 7, 10, 6, 32, 7, 135, DateTimeKind.Utc).AddTicks(9376)
                        },
                        new
                        {
                            Id = new Guid("3d739d33-7860-464c-953f-51b8a5d94935"),
                            CreatedOn = new DateTime(2024, 7, 10, 6, 32, 7, 135, DateTimeKind.Utc).AddTicks(9379),
                            Name = "Pigiama",
                            ProductSizeTypeId = new Guid("b9c10a10-806c-4db3-94ac-87a9b5657442"),
                            UpdatedOn = new DateTime(2024, 7, 10, 6, 32, 7, 135, DateTimeKind.Utc).AddTicks(9380)
                        },
                        new
                        {
                            Id = new Guid("334f3cb9-12ff-4bce-96cb-25df8350cea1"),
                            CreatedOn = new DateTime(2024, 7, 10, 6, 32, 7, 135, DateTimeKind.Utc).AddTicks(9384),
                            Name = "Top",
                            ProductSizeTypeId = new Guid("b9c10a10-806c-4db3-94ac-87a9b5657442"),
                            UpdatedOn = new DateTime(2024, 7, 10, 6, 32, 7, 135, DateTimeKind.Utc).AddTicks(9384)
                        },
                        new
                        {
                            Id = new Guid("243fe1fd-97be-4cbb-87a7-0d48afbfe0e1"),
                            CreatedOn = new DateTime(2024, 7, 10, 6, 32, 7, 135, DateTimeKind.Utc).AddTicks(9387),
                            Name = "Maglie",
                            ProductSizeTypeId = new Guid("b9c10a10-806c-4db3-94ac-87a9b5657442"),
                            UpdatedOn = new DateTime(2024, 7, 10, 6, 32, 7, 135, DateTimeKind.Utc).AddTicks(9387)
                        },
                        new
                        {
                            Id = new Guid("53c1f073-13aa-434c-9a5e-c90caeb18968"),
                            CreatedOn = new DateTime(2024, 7, 10, 6, 32, 7, 135, DateTimeKind.Utc).AddTicks(9390),
                            Name = "Pantaloni",
                            ProductSizeTypeId = new Guid("b9c10a10-806c-4db3-94ac-87a9b5657442"),
                            UpdatedOn = new DateTime(2024, 7, 10, 6, 32, 7, 135, DateTimeKind.Utc).AddTicks(9390)
                        },
                        new
                        {
                            Id = new Guid("090a5dbc-6f11-4e91-978c-8d149f5ce171"),
                            CreatedOn = new DateTime(2024, 7, 10, 6, 32, 7, 135, DateTimeKind.Utc).AddTicks(9394),
                            Name = "Salopette",
                            ProductSizeTypeId = new Guid("b9c10a10-806c-4db3-94ac-87a9b5657442"),
                            UpdatedOn = new DateTime(2024, 7, 10, 6, 32, 7, 135, DateTimeKind.Utc).AddTicks(9394)
                        },
                        new
                        {
                            Id = new Guid("3b624d59-0711-4491-9dd2-4468df8a2e0a"),
                            CreatedOn = new DateTime(2024, 7, 10, 6, 32, 7, 135, DateTimeKind.Utc).AddTicks(9397),
                            Name = "Camicia",
                            ProductSizeTypeId = new Guid("b9c10a10-806c-4db3-94ac-87a9b5657442"),
                            UpdatedOn = new DateTime(2024, 7, 10, 6, 32, 7, 135, DateTimeKind.Utc).AddTicks(9397)
                        },
                        new
                        {
                            Id = new Guid("6fc0dbd7-d812-4c1d-a194-a9f3752b90f2"),
                            CreatedOn = new DateTime(2024, 7, 10, 6, 32, 7, 135, DateTimeKind.Utc).AddTicks(9399),
                            Name = "Shorts",
                            ProductSizeTypeId = new Guid("b9c10a10-806c-4db3-94ac-87a9b5657442"),
                            UpdatedOn = new DateTime(2024, 7, 10, 6, 32, 7, 135, DateTimeKind.Utc).AddTicks(9400)
                        },
                        new
                        {
                            Id = new Guid("a863ac14-b520-458c-8f84-ab232a3a98f8"),
                            CreatedOn = new DateTime(2024, 7, 10, 6, 32, 7, 135, DateTimeKind.Utc).AddTicks(9413),
                            Name = "Giacche | Trench",
                            ProductSizeTypeId = new Guid("2870acf6-f145-4714-95b6-168588555c32"),
                            UpdatedOn = new DateTime(2024, 7, 10, 6, 32, 7, 135, DateTimeKind.Utc).AddTicks(9413)
                        },
                        new
                        {
                            Id = new Guid("6c351900-dd63-414f-b8eb-cb2cfc87b681"),
                            CreatedOn = new DateTime(2024, 7, 10, 6, 32, 7, 135, DateTimeKind.Utc).AddTicks(9416),
                            Name = "Blazer | Gilet",
                            ProductSizeTypeId = new Guid("2870acf6-f145-4714-95b6-168588555c32"),
                            UpdatedOn = new DateTime(2024, 7, 10, 6, 32, 7, 135, DateTimeKind.Utc).AddTicks(9416)
                        },
                        new
                        {
                            Id = new Guid("64058131-2521-40bf-a290-6ec24c70972d"),
                            CreatedOn = new DateTime(2024, 7, 10, 6, 32, 7, 135, DateTimeKind.Utc).AddTicks(9421),
                            Name = "Vestiti",
                            ProductSizeTypeId = new Guid("2870acf6-f145-4714-95b6-168588555c32"),
                            UpdatedOn = new DateTime(2024, 7, 10, 6, 32, 7, 135, DateTimeKind.Utc).AddTicks(9421)
                        },
                        new
                        {
                            Id = new Guid("26fdb3b0-9587-417e-aa4d-13f41abf142f"),
                            CreatedOn = new DateTime(2024, 7, 10, 6, 32, 7, 135, DateTimeKind.Utc).AddTicks(9424),
                            Name = "Body | Top",
                            ProductSizeTypeId = new Guid("2870acf6-f145-4714-95b6-168588555c32"),
                            UpdatedOn = new DateTime(2024, 7, 10, 6, 32, 7, 135, DateTimeKind.Utc).AddTicks(9424)
                        },
                        new
                        {
                            Id = new Guid("49f62b82-d574-4a44-a8b7-82b9bfffc300"),
                            CreatedOn = new DateTime(2024, 7, 10, 6, 32, 7, 135, DateTimeKind.Utc).AddTicks(9427),
                            Name = "Camicie",
                            ProductSizeTypeId = new Guid("2870acf6-f145-4714-95b6-168588555c32"),
                            UpdatedOn = new DateTime(2024, 7, 10, 6, 32, 7, 135, DateTimeKind.Utc).AddTicks(9427)
                        },
                        new
                        {
                            Id = new Guid("9317c9c5-8f08-4241-b291-577827ac3eed"),
                            CreatedOn = new DateTime(2024, 7, 10, 6, 32, 7, 135, DateTimeKind.Utc).AddTicks(9431),
                            Name = "Magliette",
                            ProductSizeTypeId = new Guid("2870acf6-f145-4714-95b6-168588555c32"),
                            UpdatedOn = new DateTime(2024, 7, 10, 6, 32, 7, 135, DateTimeKind.Utc).AddTicks(9431)
                        },
                        new
                        {
                            Id = new Guid("45e741d6-ab00-49a8-aa5a-35e20e5dd0e4"),
                            CreatedOn = new DateTime(2024, 7, 10, 6, 32, 7, 135, DateTimeKind.Utc).AddTicks(9434),
                            Name = "Felpe",
                            ProductSizeTypeId = new Guid("2870acf6-f145-4714-95b6-168588555c32"),
                            UpdatedOn = new DateTime(2024, 7, 10, 6, 32, 7, 135, DateTimeKind.Utc).AddTicks(9434)
                        },
                        new
                        {
                            Id = new Guid("5d3707bd-52bc-477f-8798-0146b579bf00"),
                            CreatedOn = new DateTime(2024, 7, 10, 6, 32, 7, 135, DateTimeKind.Utc).AddTicks(9437),
                            Name = "Gonne",
                            ProductSizeTypeId = new Guid("2870acf6-f145-4714-95b6-168588555c32"),
                            UpdatedOn = new DateTime(2024, 7, 10, 6, 32, 7, 135, DateTimeKind.Utc).AddTicks(9437)
                        },
                        new
                        {
                            Id = new Guid("48d52d38-ddfd-4adf-a5db-5bd3c9c6f8f2"),
                            CreatedOn = new DateTime(2024, 7, 10, 6, 32, 7, 135, DateTimeKind.Utc).AddTicks(9440),
                            Name = "Shorts",
                            ProductSizeTypeId = new Guid("2870acf6-f145-4714-95b6-168588555c32"),
                            UpdatedOn = new DateTime(2024, 7, 10, 6, 32, 7, 135, DateTimeKind.Utc).AddTicks(9440)
                        },
                        new
                        {
                            Id = new Guid("47d38053-4f52-458b-825f-5a06fccb719e"),
                            CreatedOn = new DateTime(2024, 7, 10, 6, 32, 7, 135, DateTimeKind.Utc).AddTicks(9443),
                            Name = "Pantaloni",
                            ProductSizeTypeId = new Guid("2870acf6-f145-4714-95b6-168588555c32"),
                            UpdatedOn = new DateTime(2024, 7, 10, 6, 32, 7, 135, DateTimeKind.Utc).AddTicks(9443)
                        },
                        new
                        {
                            Id = new Guid("35c84fe1-ae58-4177-b02d-3c5d7146e831"),
                            CreatedOn = new DateTime(2024, 7, 10, 6, 32, 7, 135, DateTimeKind.Utc).AddTicks(9473),
                            Name = "Jeans",
                            ProductSizeTypeId = new Guid("2870acf6-f145-4714-95b6-168588555c32"),
                            UpdatedOn = new DateTime(2024, 7, 10, 6, 32, 7, 135, DateTimeKind.Utc).AddTicks(9474)
                        },
                        new
                        {
                            Id = new Guid("c1157196-0f2e-4b0c-b636-7a6b1c57234c"),
                            CreatedOn = new DateTime(2024, 7, 10, 6, 32, 7, 135, DateTimeKind.Utc).AddTicks(9476),
                            Name = "Intimo",
                            ProductSizeTypeId = new Guid("2870acf6-f145-4714-95b6-168588555c32"),
                            UpdatedOn = new DateTime(2024, 7, 10, 6, 32, 7, 135, DateTimeKind.Utc).AddTicks(9477)
                        },
                        new
                        {
                            Id = new Guid("45102026-0738-4b5d-9010-347f178a254b"),
                            CreatedOn = new DateTime(2024, 7, 10, 6, 32, 7, 135, DateTimeKind.Utc).AddTicks(9479),
                            Name = "Costumi da Bagno",
                            ProductSizeTypeId = new Guid("2870acf6-f145-4714-95b6-168588555c32"),
                            UpdatedOn = new DateTime(2024, 7, 10, 6, 32, 7, 135, DateTimeKind.Utc).AddTicks(9480)
                        },
                        new
                        {
                            Id = new Guid("88e5268e-d21a-4280-bbf0-babd32712dcd"),
                            CreatedOn = new DateTime(2024, 7, 10, 6, 32, 7, 135, DateTimeKind.Utc).AddTicks(9482),
                            Name = "Polo",
                            ProductSizeTypeId = new Guid("2870acf6-f145-4714-95b6-168588555c32"),
                            UpdatedOn = new DateTime(2024, 7, 10, 6, 32, 7, 135, DateTimeKind.Utc).AddTicks(9483)
                        },
                        new
                        {
                            Id = new Guid("ee4786db-4238-4ec4-96b8-8107754ae73e"),
                            CreatedOn = new DateTime(2024, 7, 10, 6, 32, 7, 135, DateTimeKind.Utc).AddTicks(9485),
                            Name = "Maglioncini",
                            ProductSizeTypeId = new Guid("2870acf6-f145-4714-95b6-168588555c32"),
                            UpdatedOn = new DateTime(2024, 7, 10, 6, 32, 7, 135, DateTimeKind.Utc).AddTicks(9486)
                        },
                        new
                        {
                            Id = new Guid("086e5341-4419-4539-9a2d-f590fe8e8744"),
                            CreatedOn = new DateTime(2024, 7, 10, 6, 32, 7, 135, DateTimeKind.Utc).AddTicks(9498),
                            Name = "Borse",
                            ProductSizeTypeId = new Guid("bac9f80e-c261-4d89-8124-9a5c52819828"),
                            UpdatedOn = new DateTime(2024, 7, 10, 6, 32, 7, 135, DateTimeKind.Utc).AddTicks(9499)
                        },
                        new
                        {
                            Id = new Guid("166d20b2-a556-476d-8934-9313e97e3849"),
                            CreatedOn = new DateTime(2024, 7, 10, 6, 32, 7, 135, DateTimeKind.Utc).AddTicks(9502),
                            Name = "Gioielli",
                            ProductSizeTypeId = new Guid("bac9f80e-c261-4d89-8124-9a5c52819828"),
                            UpdatedOn = new DateTime(2024, 7, 10, 6, 32, 7, 135, DateTimeKind.Utc).AddTicks(9502)
                        },
                        new
                        {
                            Id = new Guid("b4c4fbde-6d2d-4445-b5d5-bf044bd70455"),
                            CreatedOn = new DateTime(2024, 7, 10, 6, 32, 7, 135, DateTimeKind.Utc).AddTicks(9504),
                            Name = "Occhiali da Sole",
                            ProductSizeTypeId = new Guid("bac9f80e-c261-4d89-8124-9a5c52819828"),
                            UpdatedOn = new DateTime(2024, 7, 10, 6, 32, 7, 135, DateTimeKind.Utc).AddTicks(9505)
                        },
                        new
                        {
                            Id = new Guid("3adf6180-d94d-4256-96a2-01d8a7d55031"),
                            CreatedOn = new DateTime(2024, 7, 10, 6, 32, 7, 135, DateTimeKind.Utc).AddTicks(9509),
                            Name = "Cappelli",
                            ProductSizeTypeId = new Guid("bac9f80e-c261-4d89-8124-9a5c52819828"),
                            UpdatedOn = new DateTime(2024, 7, 10, 6, 32, 7, 135, DateTimeKind.Utc).AddTicks(9509)
                        },
                        new
                        {
                            Id = new Guid("174c5244-e0b7-4361-b73b-b97ffb548f6e"),
                            CreatedOn = new DateTime(2024, 7, 10, 6, 32, 7, 135, DateTimeKind.Utc).AddTicks(9512),
                            Name = "Foulard",
                            ProductSizeTypeId = new Guid("bac9f80e-c261-4d89-8124-9a5c52819828"),
                            UpdatedOn = new DateTime(2024, 7, 10, 6, 32, 7, 135, DateTimeKind.Utc).AddTicks(9512)
                        },
                        new
                        {
                            Id = new Guid("c7681e5e-86e5-4ec6-8355-f3d8f0997108"),
                            CreatedOn = new DateTime(2024, 7, 10, 6, 32, 7, 135, DateTimeKind.Utc).AddTicks(9514),
                            Name = "Cinture",
                            ProductSizeTypeId = new Guid("bac9f80e-c261-4d89-8124-9a5c52819828"),
                            UpdatedOn = new DateTime(2024, 7, 10, 6, 32, 7, 135, DateTimeKind.Utc).AddTicks(9515)
                        },
                        new
                        {
                            Id = new Guid("4a11dd84-b739-4cf8-861d-51261b8bec4d"),
                            CreatedOn = new DateTime(2024, 7, 10, 6, 32, 7, 135, DateTimeKind.Utc).AddTicks(9519),
                            Name = "Orologi",
                            ProductSizeTypeId = new Guid("bac9f80e-c261-4d89-8124-9a5c52819828"),
                            UpdatedOn = new DateTime(2024, 7, 10, 6, 32, 7, 135, DateTimeKind.Utc).AddTicks(9519)
                        },
                        new
                        {
                            Id = new Guid("54b5a280-8377-4c5f-a6ab-49a4215a9558"),
                            CreatedOn = new DateTime(2024, 7, 10, 6, 32, 7, 135, DateTimeKind.Utc).AddTicks(9522),
                            Name = "Portafogli",
                            ProductSizeTypeId = new Guid("bac9f80e-c261-4d89-8124-9a5c52819828"),
                            UpdatedOn = new DateTime(2024, 7, 10, 6, 32, 7, 135, DateTimeKind.Utc).AddTicks(9522)
                        },
                        new
                        {
                            Id = new Guid("3c6170c9-ef79-423f-a258-aa7174b77728"),
                            CreatedOn = new DateTime(2024, 7, 10, 6, 32, 7, 135, DateTimeKind.Utc).AddTicks(9524),
                            Name = "Sciarpe",
                            ProductSizeTypeId = new Guid("bac9f80e-c261-4d89-8124-9a5c52819828"),
                            UpdatedOn = new DateTime(2024, 7, 10, 6, 32, 7, 135, DateTimeKind.Utc).AddTicks(9525)
                        },
                        new
                        {
                            Id = new Guid("01575160-7d19-4181-9b10-2474addee327"),
                            CreatedOn = new DateTime(2024, 7, 10, 6, 32, 7, 135, DateTimeKind.Utc).AddTicks(9527),
                            Name = "Guanti",
                            ProductSizeTypeId = new Guid("bac9f80e-c261-4d89-8124-9a5c52819828"),
                            UpdatedOn = new DateTime(2024, 7, 10, 6, 32, 7, 135, DateTimeKind.Utc).AddTicks(9527)
                        },
                        new
                        {
                            Id = new Guid("ec93efb2-b18f-4355-b1b3-8e839481273c"),
                            CreatedOn = new DateTime(2024, 7, 10, 6, 32, 7, 135, DateTimeKind.Utc).AddTicks(9530),
                            Name = "Ombrelli",
                            ProductSizeTypeId = new Guid("bac9f80e-c261-4d89-8124-9a5c52819828"),
                            UpdatedOn = new DateTime(2024, 7, 10, 6, 32, 7, 135, DateTimeKind.Utc).AddTicks(9530)
                        },
                        new
                        {
                            Id = new Guid("432bd071-e373-4692-8172-66673f8d2ce9"),
                            CreatedOn = new DateTime(2024, 7, 10, 6, 32, 7, 135, DateTimeKind.Utc).AddTicks(9544),
                            Name = "Sneakers",
                            ProductSizeTypeId = new Guid("519c79e9-5444-4109-bec6-44eec7235ba5"),
                            UpdatedOn = new DateTime(2024, 7, 10, 6, 32, 7, 135, DateTimeKind.Utc).AddTicks(9544)
                        },
                        new
                        {
                            Id = new Guid("0fb39998-716b-4f77-8da7-1dc6b679b821"),
                            CreatedOn = new DateTime(2024, 7, 10, 6, 32, 7, 135, DateTimeKind.Utc).AddTicks(9548),
                            Name = "Sandali",
                            ProductSizeTypeId = new Guid("519c79e9-5444-4109-bec6-44eec7235ba5"),
                            UpdatedOn = new DateTime(2024, 7, 10, 6, 32, 7, 135, DateTimeKind.Utc).AddTicks(9548)
                        },
                        new
                        {
                            Id = new Guid("9d48b372-1e55-4cbf-8d44-deea773b07af"),
                            CreatedOn = new DateTime(2024, 7, 10, 6, 32, 7, 135, DateTimeKind.Utc).AddTicks(9551),
                            Name = "Tacchi",
                            ProductSizeTypeId = new Guid("519c79e9-5444-4109-bec6-44eec7235ba5"),
                            UpdatedOn = new DateTime(2024, 7, 10, 6, 32, 7, 135, DateTimeKind.Utc).AddTicks(9551)
                        },
                        new
                        {
                            Id = new Guid("b7324cfa-d812-4abc-9756-53fc6ecb9bb9"),
                            CreatedOn = new DateTime(2024, 7, 10, 6, 32, 7, 135, DateTimeKind.Utc).AddTicks(9554),
                            Name = "Ciabatte",
                            ProductSizeTypeId = new Guid("519c79e9-5444-4109-bec6-44eec7235ba5"),
                            UpdatedOn = new DateTime(2024, 7, 10, 6, 32, 7, 135, DateTimeKind.Utc).AddTicks(9554)
                        },
                        new
                        {
                            Id = new Guid("5944492d-fc23-4989-bf5b-a3c3e0adac93"),
                            CreatedOn = new DateTime(2024, 7, 10, 6, 32, 7, 135, DateTimeKind.Utc).AddTicks(9557),
                            Name = "Stivaletti",
                            ProductSizeTypeId = new Guid("519c79e9-5444-4109-bec6-44eec7235ba5"),
                            UpdatedOn = new DateTime(2024, 7, 10, 6, 32, 7, 135, DateTimeKind.Utc).AddTicks(9557)
                        },
                        new
                        {
                            Id = new Guid("b77f1646-a9ad-423e-a5cd-58812b3f5f71"),
                            CreatedOn = new DateTime(2024, 7, 10, 6, 32, 7, 135, DateTimeKind.Utc).AddTicks(9560),
                            Name = "Stivali",
                            ProductSizeTypeId = new Guid("519c79e9-5444-4109-bec6-44eec7235ba5"),
                            UpdatedOn = new DateTime(2024, 7, 10, 6, 32, 7, 135, DateTimeKind.Utc).AddTicks(9560)
                        },
                        new
                        {
                            Id = new Guid("2b8dabf6-3fe1-4349-a00a-bfac68bce361"),
                            CreatedOn = new DateTime(2024, 7, 10, 6, 32, 7, 135, DateTimeKind.Utc).AddTicks(9563),
                            Name = "Ballerine",
                            ProductSizeTypeId = new Guid("519c79e9-5444-4109-bec6-44eec7235ba5"),
                            UpdatedOn = new DateTime(2024, 7, 10, 6, 32, 7, 135, DateTimeKind.Utc).AddTicks(9563)
                        },
                        new
                        {
                            Id = new Guid("664e537e-24df-4cca-9ac8-88ab2d9e1c35"),
                            CreatedOn = new DateTime(2024, 7, 10, 6, 32, 7, 135, DateTimeKind.Utc).AddTicks(9566),
                            Name = "Mare",
                            ProductSizeTypeId = new Guid("519c79e9-5444-4109-bec6-44eec7235ba5"),
                            UpdatedOn = new DateTime(2024, 7, 10, 6, 32, 7, 135, DateTimeKind.Utc).AddTicks(9566)
                        },
                        new
                        {
                            Id = new Guid("dda2df94-21cc-494f-826a-2214e1d9369b"),
                            CreatedOn = new DateTime(2024, 7, 10, 6, 32, 7, 135, DateTimeKind.Utc).AddTicks(9571),
                            Name = "Mocassini",
                            ProductSizeTypeId = new Guid("519c79e9-5444-4109-bec6-44eec7235ba5"),
                            UpdatedOn = new DateTime(2024, 7, 10, 6, 32, 7, 135, DateTimeKind.Utc).AddTicks(9571)
                        },
                        new
                        {
                            Id = new Guid("dadfde15-8ab9-400a-afab-b3fe38504b30"),
                            CreatedOn = new DateTime(2024, 7, 10, 6, 32, 7, 135, DateTimeKind.Utc).AddTicks(9574),
                            Name = "Basse",
                            ProductSizeTypeId = new Guid("519c79e9-5444-4109-bec6-44eec7235ba5"),
                            UpdatedOn = new DateTime(2024, 7, 10, 6, 32, 7, 135, DateTimeKind.Utc).AddTicks(9574)
                        },
                        new
                        {
                            Id = new Guid("ceda27fd-1a98-4d0d-bec9-4eb5867938b2"),
                            CreatedOn = new DateTime(2024, 7, 10, 6, 32, 7, 135, DateTimeKind.Utc).AddTicks(9576),
                            Name = "Cerimonia",
                            ProductSizeTypeId = new Guid("519c79e9-5444-4109-bec6-44eec7235ba5"),
                            UpdatedOn = new DateTime(2024, 7, 10, 6, 32, 7, 135, DateTimeKind.Utc).AddTicks(9577)
                        },
                        new
                        {
                            Id = new Guid("e3d1ae82-0fb2-475f-b648-8b04c194d7aa"),
                            CreatedOn = new DateTime(2024, 7, 10, 6, 32, 7, 135, DateTimeKind.Utc).AddTicks(9588),
                            Name = "Sneakers",
                            ProductSizeTypeId = new Guid("3e13d40c-6b24-4c7f-90fc-d5654e42a2a1"),
                            UpdatedOn = new DateTime(2024, 7, 10, 6, 32, 7, 135, DateTimeKind.Utc).AddTicks(9588)
                        },
                        new
                        {
                            Id = new Guid("063798c4-b562-44d1-9365-49dfac325675"),
                            CreatedOn = new DateTime(2024, 7, 10, 6, 32, 7, 135, DateTimeKind.Utc).AddTicks(9592),
                            Name = "Sandali",
                            ProductSizeTypeId = new Guid("3e13d40c-6b24-4c7f-90fc-d5654e42a2a1"),
                            UpdatedOn = new DateTime(2024, 7, 10, 6, 32, 7, 135, DateTimeKind.Utc).AddTicks(9592)
                        },
                        new
                        {
                            Id = new Guid("7fcc62ad-2009-4caa-8a1f-763797007bf2"),
                            CreatedOn = new DateTime(2024, 7, 10, 6, 32, 7, 135, DateTimeKind.Utc).AddTicks(9595),
                            Name = "Ciabatte",
                            ProductSizeTypeId = new Guid("3e13d40c-6b24-4c7f-90fc-d5654e42a2a1"),
                            UpdatedOn = new DateTime(2024, 7, 10, 6, 32, 7, 135, DateTimeKind.Utc).AddTicks(9595)
                        },
                        new
                        {
                            Id = new Guid("808af10d-c5a0-4959-8919-fdf4135053dc"),
                            CreatedOn = new DateTime(2024, 7, 10, 6, 32, 7, 135, DateTimeKind.Utc).AddTicks(9597),
                            Name = "Stivaletti",
                            ProductSizeTypeId = new Guid("3e13d40c-6b24-4c7f-90fc-d5654e42a2a1"),
                            UpdatedOn = new DateTime(2024, 7, 10, 6, 32, 7, 135, DateTimeKind.Utc).AddTicks(9598)
                        },
                        new
                        {
                            Id = new Guid("e451fa7d-c237-41bd-96c5-34981d7b1524"),
                            CreatedOn = new DateTime(2024, 7, 10, 6, 32, 7, 135, DateTimeKind.Utc).AddTicks(9600),
                            Name = "Stivali",
                            ProductSizeTypeId = new Guid("3e13d40c-6b24-4c7f-90fc-d5654e42a2a1"),
                            UpdatedOn = new DateTime(2024, 7, 10, 6, 32, 7, 135, DateTimeKind.Utc).AddTicks(9600)
                        },
                        new
                        {
                            Id = new Guid("920ec65b-5903-4465-aa4c-ae6afefcc79d"),
                            CreatedOn = new DateTime(2024, 7, 10, 6, 32, 7, 135, DateTimeKind.Utc).AddTicks(9605),
                            Name = "Mare",
                            ProductSizeTypeId = new Guid("3e13d40c-6b24-4c7f-90fc-d5654e42a2a1"),
                            UpdatedOn = new DateTime(2024, 7, 10, 6, 32, 7, 135, DateTimeKind.Utc).AddTicks(9605)
                        },
                        new
                        {
                            Id = new Guid("e2667c16-e328-45aa-a416-9a04cb234fdf"),
                            CreatedOn = new DateTime(2024, 7, 10, 6, 32, 7, 135, DateTimeKind.Utc).AddTicks(9608),
                            Name = "Sportive",
                            ProductSizeTypeId = new Guid("3e13d40c-6b24-4c7f-90fc-d5654e42a2a1"),
                            UpdatedOn = new DateTime(2024, 7, 10, 6, 32, 7, 135, DateTimeKind.Utc).AddTicks(9608)
                        },
                        new
                        {
                            Id = new Guid("c162f611-ee91-4823-95e6-c0548e0aafc4"),
                            CreatedOn = new DateTime(2024, 7, 10, 6, 32, 7, 135, DateTimeKind.Utc).AddTicks(9610),
                            Name = "Cerimonia",
                            ProductSizeTypeId = new Guid("3e13d40c-6b24-4c7f-90fc-d5654e42a2a1"),
                            UpdatedOn = new DateTime(2024, 7, 10, 6, 32, 7, 135, DateTimeKind.Utc).AddTicks(9611)
                        });
                });

            modelBuilder.Entity("Troonch.Sales.Domain.Entities.ProductGender", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<DateTime>("UpdatedOn")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("ProductGenders");

                    b.HasData(
                        new
                        {
                            Id = new Guid("0e3f5c60-048b-4347-b344-a1a4e26553fa"),
                            CreatedOn = new DateTime(2024, 7, 10, 6, 32, 7, 135, DateTimeKind.Utc).AddTicks(8680),
                            Name = "Uomo",
                            UpdatedOn = new DateTime(2024, 7, 10, 6, 32, 7, 135, DateTimeKind.Utc).AddTicks(8683)
                        },
                        new
                        {
                            Id = new Guid("4188e08c-dc8c-40fd-9ae1-8ef4a533e5d1"),
                            CreatedOn = new DateTime(2024, 7, 10, 6, 32, 7, 135, DateTimeKind.Utc).AddTicks(8686),
                            Name = "Donna",
                            UpdatedOn = new DateTime(2024, 7, 10, 6, 32, 7, 135, DateTimeKind.Utc).AddTicks(8686)
                        },
                        new
                        {
                            Id = new Guid("78414112-893f-48cb-b0fd-3ac78f7c3bf1"),
                            CreatedOn = new DateTime(2024, 7, 10, 6, 32, 7, 135, DateTimeKind.Utc).AddTicks(8687),
                            Name = "Bambino",
                            UpdatedOn = new DateTime(2024, 7, 10, 6, 32, 7, 135, DateTimeKind.Utc).AddTicks(8688)
                        },
                        new
                        {
                            Id = new Guid("b3fd62d4-337d-49ad-aa7d-812a6c742663"),
                            CreatedOn = new DateTime(2024, 7, 10, 6, 32, 7, 135, DateTimeKind.Utc).AddTicks(8689),
                            Name = "Bambina",
                            UpdatedOn = new DateTime(2024, 7, 10, 6, 32, 7, 135, DateTimeKind.Utc).AddTicks(8689)
                        },
                        new
                        {
                            Id = new Guid("dc874f0a-f221-4897-82fb-8edba4215e95"),
                            CreatedOn = new DateTime(2024, 7, 10, 6, 32, 7, 135, DateTimeKind.Utc).AddTicks(8692),
                            Name = "Neonato",
                            UpdatedOn = new DateTime(2024, 7, 10, 6, 32, 7, 135, DateTimeKind.Utc).AddTicks(8692)
                        });
                });

            modelBuilder.Entity("Troonch.Sales.Domain.Entities.ProductGenderSizeTypeLookup", b =>
                {
                    b.Property<Guid>("ProductGenderId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ProductSizeTypeId")
                        .HasColumnType("char(36)");

                    b.HasKey("ProductGenderId", "ProductSizeTypeId");

                    b.HasIndex("ProductSizeTypeId");

                    b.ToTable("ProductGenderSizeTypeLookup");
                });

            modelBuilder.Entity("Troonch.Sales.Domain.Entities.ProductItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Barcode")
                        .HasMaxLength(30)
                        .IsUnicode(true)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("Color")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Currency")
                        .HasColumnType("int");

                    b.Property<decimal>("OriginalPrice")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<Guid>("ProductId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ProductSizeOptionId")
                        .HasColumnType("char(36)");

                    b.Property<int>("QuantityAvailable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<decimal>("SalePrice")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<DateTime>("UpdatedOn")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("Barcode")
                        .IsUnique();

                    b.HasIndex("ProductId");

                    b.HasIndex("ProductSizeOptionId");

                    b.ToTable("ProductItems");
                });

            modelBuilder.Entity("Troonch.Sales.Domain.Entities.ProductMaterial", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("UpdatedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.HasKey("Id");

                    b.ToTable("ProductMaterials");

                    b.HasData(
                        new
                        {
                            Id = new Guid("aca9122c-a17b-4a3c-8913-c0fb0801b2d5"),
                            CreatedOn = new DateTime(2024, 7, 10, 6, 32, 7, 135, DateTimeKind.Utc).AddTicks(8781),
                            UpdatedOn = new DateTime(2024, 7, 10, 6, 32, 7, 135, DateTimeKind.Utc).AddTicks(8782),
                            Value = "Cotone"
                        },
                        new
                        {
                            Id = new Guid("944556e2-43ad-4ce0-a9df-a568ec2b9da3"),
                            CreatedOn = new DateTime(2024, 7, 10, 6, 32, 7, 135, DateTimeKind.Utc).AddTicks(8785),
                            UpdatedOn = new DateTime(2024, 7, 10, 6, 32, 7, 135, DateTimeKind.Utc).AddTicks(8786),
                            Value = "Lana"
                        },
                        new
                        {
                            Id = new Guid("26b1aacf-51cd-4f3d-ba19-ce62f0800a8b"),
                            CreatedOn = new DateTime(2024, 7, 10, 6, 32, 7, 135, DateTimeKind.Utc).AddTicks(8800),
                            UpdatedOn = new DateTime(2024, 7, 10, 6, 32, 7, 135, DateTimeKind.Utc).AddTicks(8800),
                            Value = "Seta"
                        },
                        new
                        {
                            Id = new Guid("f118b361-5523-4499-8ce8-e3c330b648a4"),
                            CreatedOn = new DateTime(2024, 7, 10, 6, 32, 7, 135, DateTimeKind.Utc).AddTicks(8802),
                            UpdatedOn = new DateTime(2024, 7, 10, 6, 32, 7, 135, DateTimeKind.Utc).AddTicks(8802),
                            Value = "Lino"
                        },
                        new
                        {
                            Id = new Guid("c2968670-3385-4234-b4f6-86d2b7cad132"),
                            CreatedOn = new DateTime(2024, 7, 10, 6, 32, 7, 135, DateTimeKind.Utc).AddTicks(8804),
                            UpdatedOn = new DateTime(2024, 7, 10, 6, 32, 7, 135, DateTimeKind.Utc).AddTicks(8804),
                            Value = "Canapa"
                        },
                        new
                        {
                            Id = new Guid("468a4817-7f07-431a-8967-8f97b8f378c7"),
                            CreatedOn = new DateTime(2024, 7, 10, 6, 32, 7, 135, DateTimeKind.Utc).AddTicks(8807),
                            UpdatedOn = new DateTime(2024, 7, 10, 6, 32, 7, 135, DateTimeKind.Utc).AddTicks(8807),
                            Value = "Bamboo"
                        });
                });

            modelBuilder.Entity("Troonch.Sales.Domain.Entities.ProductSizeOption", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("ProductSizeTypeId")
                        .HasColumnType("char(36)");

                    b.Property<int>("Sort")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("ProductSizeTypeId");

                    b.ToTable("ProductSizeOptions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("462780bb-247b-40be-b70d-72644124bbe4"),
                            CreatedOn = new DateTime(2024, 7, 10, 6, 32, 7, 135, DateTimeKind.Utc).AddTicks(8957),
                            ProductSizeTypeId = new Guid("bac9f80e-c261-4d89-8124-9a5c52819828"),
                            Sort = 1,
                            UpdatedOn = new DateTime(2024, 7, 10, 6, 32, 7, 135, DateTimeKind.Utc).AddTicks(8958),
                            Value = "Taglia Unica"
                        },
                        new
                        {
                            Id = new Guid("131283fa-bc71-4bb0-b1d3-b83db8bddda2"),
                            CreatedOn = new DateTime(2024, 7, 10, 6, 32, 7, 135, DateTimeKind.Utc).AddTicks(8983),
                            ProductSizeTypeId = new Guid("519c79e9-5444-4109-bec6-44eec7235ba5"),
                            Sort = 1,
                            UpdatedOn = new DateTime(2024, 7, 10, 6, 32, 7, 135, DateTimeKind.Utc).AddTicks(8983),
                            Value = "35"
                        },
                        new
                        {
                            Id = new Guid("0b81185d-a24d-47c9-83a7-5cfba9ed7288"),
                            CreatedOn = new DateTime(2024, 7, 10, 6, 32, 7, 135, DateTimeKind.Utc).AddTicks(8988),
                            ProductSizeTypeId = new Guid("519c79e9-5444-4109-bec6-44eec7235ba5"),
                            Sort = 2,
                            UpdatedOn = new DateTime(2024, 7, 10, 6, 32, 7, 135, DateTimeKind.Utc).AddTicks(8988),
                            Value = "36"
                        },
                        new
                        {
                            Id = new Guid("ffced20c-0677-49bc-8d4d-8ce48c55e04c"),
                            CreatedOn = new DateTime(2024, 7, 10, 6, 32, 7, 135, DateTimeKind.Utc).AddTicks(8992),
                            ProductSizeTypeId = new Guid("519c79e9-5444-4109-bec6-44eec7235ba5"),
                            Sort = 3,
                            UpdatedOn = new DateTime(2024, 7, 10, 6, 32, 7, 135, DateTimeKind.Utc).AddTicks(8992),
                            Value = "37"
                        },
                        new
                        {
                            Id = new Guid("4ba12a88-20ef-4675-a5da-c849e95f3926"),
                            CreatedOn = new DateTime(2024, 7, 10, 6, 32, 7, 135, DateTimeKind.Utc).AddTicks(8995),
                            ProductSizeTypeId = new Guid("519c79e9-5444-4109-bec6-44eec7235ba5"),
                            Sort = 4,
                            UpdatedOn = new DateTime(2024, 7, 10, 6, 32, 7, 135, DateTimeKind.Utc).AddTicks(8996),
                            Value = "38"
                        },
                        new
                        {
                            Id = new Guid("798d6a95-6322-400c-9c10-15687dadcc0a"),
                            CreatedOn = new DateTime(2024, 7, 10, 6, 32, 7, 135, DateTimeKind.Utc).AddTicks(9000),
                            ProductSizeTypeId = new Guid("519c79e9-5444-4109-bec6-44eec7235ba5"),
                            Sort = 5,
                            UpdatedOn = new DateTime(2024, 7, 10, 6, 32, 7, 135, DateTimeKind.Utc).AddTicks(9000),
                            Value = "39"
                        },
                        new
                        {
                            Id = new Guid("3065692e-eccf-43f8-b296-c40593f0b0ed"),
                            CreatedOn = new DateTime(2024, 7, 10, 6, 32, 7, 135, DateTimeKind.Utc).AddTicks(9003),
                            ProductSizeTypeId = new Guid("519c79e9-5444-4109-bec6-44eec7235ba5"),
                            Sort = 6,
                            UpdatedOn = new DateTime(2024, 7, 10, 6, 32, 7, 135, DateTimeKind.Utc).AddTicks(9004),
                            Value = "40"
                        },
                        new
                        {
                            Id = new Guid("ba3b6b2b-e323-4990-87bd-5c747b8780ab"),
                            CreatedOn = new DateTime(2024, 7, 10, 6, 32, 7, 135, DateTimeKind.Utc).AddTicks(9010),
                            ProductSizeTypeId = new Guid("519c79e9-5444-4109-bec6-44eec7235ba5"),
                            Sort = 7,
                            UpdatedOn = new DateTime(2024, 7, 10, 6, 32, 7, 135, DateTimeKind.Utc).AddTicks(9011),
                            Value = "41"
                        },
                        new
                        {
                            Id = new Guid("066bdd5d-fa22-49c7-906a-999beb5af96c"),
                            CreatedOn = new DateTime(2024, 7, 10, 6, 32, 7, 135, DateTimeKind.Utc).AddTicks(9014),
                            ProductSizeTypeId = new Guid("519c79e9-5444-4109-bec6-44eec7235ba5"),
                            Sort = 8,
                            UpdatedOn = new DateTime(2024, 7, 10, 6, 32, 7, 135, DateTimeKind.Utc).AddTicks(9014),
                            Value = "42"
                        },
                        new
                        {
                            Id = new Guid("3126025f-4205-4127-bbe3-de6116c09bf1"),
                            CreatedOn = new DateTime(2024, 7, 10, 6, 32, 7, 135, DateTimeKind.Utc).AddTicks(9019),
                            ProductSizeTypeId = new Guid("519c79e9-5444-4109-bec6-44eec7235ba5"),
                            Sort = 9,
                            UpdatedOn = new DateTime(2024, 7, 10, 6, 32, 7, 135, DateTimeKind.Utc).AddTicks(9019),
                            Value = "43"
                        },
                        new
                        {
                            Id = new Guid("8180c529-019b-4143-957d-ac4c4e4c3a81"),
                            CreatedOn = new DateTime(2024, 7, 10, 6, 32, 7, 135, DateTimeKind.Utc).AddTicks(9022),
                            ProductSizeTypeId = new Guid("519c79e9-5444-4109-bec6-44eec7235ba5"),
                            Sort = 10,
                            UpdatedOn = new DateTime(2024, 7, 10, 6, 32, 7, 135, DateTimeKind.Utc).AddTicks(9023),
                            Value = "44"
                        },
                        new
                        {
                            Id = new Guid("e457cd6d-8c7a-4931-80b4-3c665aaf04c5"),
                            CreatedOn = new DateTime(2024, 7, 10, 6, 32, 7, 135, DateTimeKind.Utc).AddTicks(9026),
                            ProductSizeTypeId = new Guid("519c79e9-5444-4109-bec6-44eec7235ba5"),
                            Sort = 11,
                            UpdatedOn = new DateTime(2024, 7, 10, 6, 32, 7, 135, DateTimeKind.Utc).AddTicks(9026),
                            Value = "45"
                        },
                        new
                        {
                            Id = new Guid("83f498c1-5e93-42f7-8b35-65766cfebe12"),
                            CreatedOn = new DateTime(2024, 7, 10, 6, 32, 7, 135, DateTimeKind.Utc).AddTicks(9030),
                            ProductSizeTypeId = new Guid("519c79e9-5444-4109-bec6-44eec7235ba5"),
                            Sort = 12,
                            UpdatedOn = new DateTime(2024, 7, 10, 6, 32, 7, 135, DateTimeKind.Utc).AddTicks(9030),
                            Value = "46"
                        },
                        new
                        {
                            Id = new Guid("c70188d6-0426-4a69-9006-a54ec2a23b24"),
                            CreatedOn = new DateTime(2024, 7, 10, 6, 32, 7, 135, DateTimeKind.Utc).AddTicks(9042),
                            ProductSizeTypeId = new Guid("3e13d40c-6b24-4c7f-90fc-d5654e42a2a1"),
                            Sort = 1,
                            UpdatedOn = new DateTime(2024, 7, 10, 6, 32, 7, 135, DateTimeKind.Utc).AddTicks(9043),
                            Value = "14"
                        },
                        new
                        {
                            Id = new Guid("23acc23d-8db9-477a-b55b-c61ef8aae22b"),
                            CreatedOn = new DateTime(2024, 7, 10, 6, 32, 7, 135, DateTimeKind.Utc).AddTicks(9047),
                            ProductSizeTypeId = new Guid("3e13d40c-6b24-4c7f-90fc-d5654e42a2a1"),
                            Sort = 2,
                            UpdatedOn = new DateTime(2024, 7, 10, 6, 32, 7, 135, DateTimeKind.Utc).AddTicks(9047),
                            Value = "15"
                        },
                        new
                        {
                            Id = new Guid("52440b1c-7a4f-4481-9925-41a6019c162c"),
                            CreatedOn = new DateTime(2024, 7, 10, 6, 32, 7, 135, DateTimeKind.Utc).AddTicks(9052),
                            ProductSizeTypeId = new Guid("3e13d40c-6b24-4c7f-90fc-d5654e42a2a1"),
                            Sort = 3,
                            UpdatedOn = new DateTime(2024, 7, 10, 6, 32, 7, 135, DateTimeKind.Utc).AddTicks(9052),
                            Value = "16"
                        },
                        new
                        {
                            Id = new Guid("598dc821-c0ee-495a-be7f-5c5fabe39d68"),
                            CreatedOn = new DateTime(2024, 7, 10, 6, 32, 7, 135, DateTimeKind.Utc).AddTicks(9056),
                            ProductSizeTypeId = new Guid("3e13d40c-6b24-4c7f-90fc-d5654e42a2a1"),
                            Sort = 4,
                            UpdatedOn = new DateTime(2024, 7, 10, 6, 32, 7, 135, DateTimeKind.Utc).AddTicks(9056),
                            Value = "17"
                        },
                        new
                        {
                            Id = new Guid("dd0a027c-d1f2-4204-9f08-62849bce3caa"),
                            CreatedOn = new DateTime(2024, 7, 10, 6, 32, 7, 135, DateTimeKind.Utc).AddTicks(9060),
                            ProductSizeTypeId = new Guid("3e13d40c-6b24-4c7f-90fc-d5654e42a2a1"),
                            Sort = 5,
                            UpdatedOn = new DateTime(2024, 7, 10, 6, 32, 7, 135, DateTimeKind.Utc).AddTicks(9061),
                            Value = "18"
                        },
                        new
                        {
                            Id = new Guid("6f25f3ea-2f72-400c-86d2-8390b6d8531b"),
                            CreatedOn = new DateTime(2024, 7, 10, 6, 32, 7, 135, DateTimeKind.Utc).AddTicks(9064),
                            ProductSizeTypeId = new Guid("3e13d40c-6b24-4c7f-90fc-d5654e42a2a1"),
                            Sort = 6,
                            UpdatedOn = new DateTime(2024, 7, 10, 6, 32, 7, 135, DateTimeKind.Utc).AddTicks(9064),
                            Value = "19"
                        },
                        new
                        {
                            Id = new Guid("86fa4630-afad-4c7b-8c2f-81dfd819c20c"),
                            CreatedOn = new DateTime(2024, 7, 10, 6, 32, 7, 135, DateTimeKind.Utc).AddTicks(9067),
                            ProductSizeTypeId = new Guid("3e13d40c-6b24-4c7f-90fc-d5654e42a2a1"),
                            Sort = 7,
                            UpdatedOn = new DateTime(2024, 7, 10, 6, 32, 7, 135, DateTimeKind.Utc).AddTicks(9068),
                            Value = "20"
                        },
                        new
                        {
                            Id = new Guid("0f267bcf-9505-4bcc-af18-a6b5745b4eff"),
                            CreatedOn = new DateTime(2024, 7, 10, 6, 32, 7, 135, DateTimeKind.Utc).AddTicks(9071),
                            ProductSizeTypeId = new Guid("3e13d40c-6b24-4c7f-90fc-d5654e42a2a1"),
                            Sort = 8,
                            UpdatedOn = new DateTime(2024, 7, 10, 6, 32, 7, 135, DateTimeKind.Utc).AddTicks(9071),
                            Value = "21"
                        },
                        new
                        {
                            Id = new Guid("3cab32ec-d258-4ce1-b6b7-062761795066"),
                            CreatedOn = new DateTime(2024, 7, 10, 6, 32, 7, 135, DateTimeKind.Utc).AddTicks(9074),
                            ProductSizeTypeId = new Guid("3e13d40c-6b24-4c7f-90fc-d5654e42a2a1"),
                            Sort = 9,
                            UpdatedOn = new DateTime(2024, 7, 10, 6, 32, 7, 135, DateTimeKind.Utc).AddTicks(9075),
                            Value = "22"
                        },
                        new
                        {
                            Id = new Guid("18977de6-5c2d-4c10-b722-5e423af4cfbc"),
                            CreatedOn = new DateTime(2024, 7, 10, 6, 32, 7, 135, DateTimeKind.Utc).AddTicks(9078),
                            ProductSizeTypeId = new Guid("3e13d40c-6b24-4c7f-90fc-d5654e42a2a1"),
                            Sort = 10,
                            UpdatedOn = new DateTime(2024, 7, 10, 6, 32, 7, 135, DateTimeKind.Utc).AddTicks(9078),
                            Value = "23"
                        },
                        new
                        {
                            Id = new Guid("61151ae8-efa6-4daa-b423-95507d5a3b24"),
                            CreatedOn = new DateTime(2024, 7, 10, 6, 32, 7, 135, DateTimeKind.Utc).AddTicks(9083),
                            ProductSizeTypeId = new Guid("3e13d40c-6b24-4c7f-90fc-d5654e42a2a1"),
                            Sort = 11,
                            UpdatedOn = new DateTime(2024, 7, 10, 6, 32, 7, 135, DateTimeKind.Utc).AddTicks(9083),
                            Value = "24"
                        },
                        new
                        {
                            Id = new Guid("2b6f5ec1-15f8-40c9-a826-c136df9309e2"),
                            CreatedOn = new DateTime(2024, 7, 10, 6, 32, 7, 135, DateTimeKind.Utc).AddTicks(9087),
                            ProductSizeTypeId = new Guid("3e13d40c-6b24-4c7f-90fc-d5654e42a2a1"),
                            Sort = 12,
                            UpdatedOn = new DateTime(2024, 7, 10, 6, 32, 7, 135, DateTimeKind.Utc).AddTicks(9088),
                            Value = "25"
                        },
                        new
                        {
                            Id = new Guid("0887bf64-78e1-4adc-9f08-10c2d1affd7a"),
                            CreatedOn = new DateTime(2024, 7, 10, 6, 32, 7, 135, DateTimeKind.Utc).AddTicks(9091),
                            ProductSizeTypeId = new Guid("3e13d40c-6b24-4c7f-90fc-d5654e42a2a1"),
                            Sort = 13,
                            UpdatedOn = new DateTime(2024, 7, 10, 6, 32, 7, 135, DateTimeKind.Utc).AddTicks(9091),
                            Value = "26"
                        },
                        new
                        {
                            Id = new Guid("e05f210f-2a6e-4e85-af99-f598c0dc3deb"),
                            CreatedOn = new DateTime(2024, 7, 10, 6, 32, 7, 135, DateTimeKind.Utc).AddTicks(9094),
                            ProductSizeTypeId = new Guid("3e13d40c-6b24-4c7f-90fc-d5654e42a2a1"),
                            Sort = 14,
                            UpdatedOn = new DateTime(2024, 7, 10, 6, 32, 7, 135, DateTimeKind.Utc).AddTicks(9094),
                            Value = "27"
                        },
                        new
                        {
                            Id = new Guid("76e8e6e6-73c3-408b-96c9-1f0d93ab1a08"),
                            CreatedOn = new DateTime(2024, 7, 10, 6, 32, 7, 135, DateTimeKind.Utc).AddTicks(9098),
                            ProductSizeTypeId = new Guid("3e13d40c-6b24-4c7f-90fc-d5654e42a2a1"),
                            Sort = 15,
                            UpdatedOn = new DateTime(2024, 7, 10, 6, 32, 7, 135, DateTimeKind.Utc).AddTicks(9098),
                            Value = "28"
                        },
                        new
                        {
                            Id = new Guid("4f624396-fa8e-4f73-97c9-b4af9a90e84b"),
                            CreatedOn = new DateTime(2024, 7, 10, 6, 32, 7, 135, DateTimeKind.Utc).AddTicks(9101),
                            ProductSizeTypeId = new Guid("3e13d40c-6b24-4c7f-90fc-d5654e42a2a1"),
                            Sort = 16,
                            UpdatedOn = new DateTime(2024, 7, 10, 6, 32, 7, 135, DateTimeKind.Utc).AddTicks(9101),
                            Value = "29"
                        },
                        new
                        {
                            Id = new Guid("b8e12f0a-f132-4f1a-812c-fe9e1e5edf9d"),
                            CreatedOn = new DateTime(2024, 7, 10, 6, 32, 7, 135, DateTimeKind.Utc).AddTicks(9104),
                            ProductSizeTypeId = new Guid("3e13d40c-6b24-4c7f-90fc-d5654e42a2a1"),
                            Sort = 17,
                            UpdatedOn = new DateTime(2024, 7, 10, 6, 32, 7, 135, DateTimeKind.Utc).AddTicks(9104),
                            Value = "30"
                        },
                        new
                        {
                            Id = new Guid("833bc394-9239-4a1f-9fc8-70880d8fd13c"),
                            CreatedOn = new DateTime(2024, 7, 10, 6, 32, 7, 135, DateTimeKind.Utc).AddTicks(9107),
                            ProductSizeTypeId = new Guid("3e13d40c-6b24-4c7f-90fc-d5654e42a2a1"),
                            Sort = 18,
                            UpdatedOn = new DateTime(2024, 7, 10, 6, 32, 7, 135, DateTimeKind.Utc).AddTicks(9108),
                            Value = "31"
                        },
                        new
                        {
                            Id = new Guid("42a58a83-2d16-43c4-9148-942e18cec4ca"),
                            CreatedOn = new DateTime(2024, 7, 10, 6, 32, 7, 135, DateTimeKind.Utc).AddTicks(9112),
                            ProductSizeTypeId = new Guid("3e13d40c-6b24-4c7f-90fc-d5654e42a2a1"),
                            Sort = 19,
                            UpdatedOn = new DateTime(2024, 7, 10, 6, 32, 7, 135, DateTimeKind.Utc).AddTicks(9113),
                            Value = "32"
                        },
                        new
                        {
                            Id = new Guid("089ef285-6c22-4904-ac18-17a4b9761046"),
                            CreatedOn = new DateTime(2024, 7, 10, 6, 32, 7, 135, DateTimeKind.Utc).AddTicks(9116),
                            ProductSizeTypeId = new Guid("3e13d40c-6b24-4c7f-90fc-d5654e42a2a1"),
                            Sort = 20,
                            UpdatedOn = new DateTime(2024, 7, 10, 6, 32, 7, 135, DateTimeKind.Utc).AddTicks(9116),
                            Value = "33"
                        },
                        new
                        {
                            Id = new Guid("a9fce661-3230-409c-afe7-bab74375291e"),
                            CreatedOn = new DateTime(2024, 7, 10, 6, 32, 7, 135, DateTimeKind.Utc).AddTicks(9149),
                            ProductSizeTypeId = new Guid("3e13d40c-6b24-4c7f-90fc-d5654e42a2a1"),
                            Sort = 21,
                            UpdatedOn = new DateTime(2024, 7, 10, 6, 32, 7, 135, DateTimeKind.Utc).AddTicks(9149),
                            Value = "34"
                        },
                        new
                        {
                            Id = new Guid("32e1a590-a3a2-4cd1-8fd1-deb4b1ec4a63"),
                            CreatedOn = new DateTime(2024, 7, 10, 6, 32, 7, 135, DateTimeKind.Utc).AddTicks(9163),
                            ProductSizeTypeId = new Guid("2870acf6-f145-4714-95b6-168588555c32"),
                            Sort = 1,
                            UpdatedOn = new DateTime(2024, 7, 10, 6, 32, 7, 135, DateTimeKind.Utc).AddTicks(9163),
                            Value = "XXS"
                        },
                        new
                        {
                            Id = new Guid("b2a97de3-d669-4ea4-aa2d-1f58ac1a6c63"),
                            CreatedOn = new DateTime(2024, 7, 10, 6, 32, 7, 135, DateTimeKind.Utc).AddTicks(9167),
                            ProductSizeTypeId = new Guid("2870acf6-f145-4714-95b6-168588555c32"),
                            Sort = 2,
                            UpdatedOn = new DateTime(2024, 7, 10, 6, 32, 7, 135, DateTimeKind.Utc).AddTicks(9167),
                            Value = "XS"
                        },
                        new
                        {
                            Id = new Guid("2621d23a-79c4-41d7-bf85-0023ba811934"),
                            CreatedOn = new DateTime(2024, 7, 10, 6, 32, 7, 135, DateTimeKind.Utc).AddTicks(9170),
                            ProductSizeTypeId = new Guid("2870acf6-f145-4714-95b6-168588555c32"),
                            Sort = 3,
                            UpdatedOn = new DateTime(2024, 7, 10, 6, 32, 7, 135, DateTimeKind.Utc).AddTicks(9170),
                            Value = "S"
                        },
                        new
                        {
                            Id = new Guid("810b9982-d05c-45d5-a84e-05288fe9d547"),
                            CreatedOn = new DateTime(2024, 7, 10, 6, 32, 7, 135, DateTimeKind.Utc).AddTicks(9173),
                            ProductSizeTypeId = new Guid("2870acf6-f145-4714-95b6-168588555c32"),
                            Sort = 4,
                            UpdatedOn = new DateTime(2024, 7, 10, 6, 32, 7, 135, DateTimeKind.Utc).AddTicks(9173),
                            Value = "M"
                        },
                        new
                        {
                            Id = new Guid("16e5c269-b20c-4ffe-8747-89a1b8d5be62"),
                            CreatedOn = new DateTime(2024, 7, 10, 6, 32, 7, 135, DateTimeKind.Utc).AddTicks(9176),
                            ProductSizeTypeId = new Guid("2870acf6-f145-4714-95b6-168588555c32"),
                            Sort = 5,
                            UpdatedOn = new DateTime(2024, 7, 10, 6, 32, 7, 135, DateTimeKind.Utc).AddTicks(9176),
                            Value = "L"
                        },
                        new
                        {
                            Id = new Guid("3eff79d1-9b39-43c2-b733-667d6447d405"),
                            CreatedOn = new DateTime(2024, 7, 10, 6, 32, 7, 135, DateTimeKind.Utc).AddTicks(9181),
                            ProductSizeTypeId = new Guid("2870acf6-f145-4714-95b6-168588555c32"),
                            Sort = 6,
                            UpdatedOn = new DateTime(2024, 7, 10, 6, 32, 7, 135, DateTimeKind.Utc).AddTicks(9181),
                            Value = "XL"
                        },
                        new
                        {
                            Id = new Guid("e4ebceb7-02f3-4282-8cb7-376a3cfce266"),
                            CreatedOn = new DateTime(2024, 7, 10, 6, 32, 7, 135, DateTimeKind.Utc).AddTicks(9183),
                            ProductSizeTypeId = new Guid("2870acf6-f145-4714-95b6-168588555c32"),
                            Sort = 7,
                            UpdatedOn = new DateTime(2024, 7, 10, 6, 32, 7, 135, DateTimeKind.Utc).AddTicks(9184),
                            Value = "XXL"
                        },
                        new
                        {
                            Id = new Guid("591391ad-ef0c-46f7-ac01-1123da689ede"),
                            CreatedOn = new DateTime(2024, 7, 10, 6, 32, 7, 135, DateTimeKind.Utc).AddTicks(9186),
                            ProductSizeTypeId = new Guid("2870acf6-f145-4714-95b6-168588555c32"),
                            Sort = 8,
                            UpdatedOn = new DateTime(2024, 7, 10, 6, 32, 7, 135, DateTimeKind.Utc).AddTicks(9186),
                            Value = "XXXL"
                        },
                        new
                        {
                            Id = new Guid("0a2f330e-d61a-424f-a3bb-0874f03a9162"),
                            CreatedOn = new DateTime(2024, 7, 10, 6, 32, 7, 135, DateTimeKind.Utc).AddTicks(9202),
                            ProductSizeTypeId = new Guid("b9c10a10-806c-4db3-94ac-87a9b5657442"),
                            Sort = 1,
                            UpdatedOn = new DateTime(2024, 7, 10, 6, 32, 7, 135, DateTimeKind.Utc).AddTicks(9202),
                            Value = "4M"
                        },
                        new
                        {
                            Id = new Guid("964b412c-d4d7-4e9c-8519-163141fd5093"),
                            CreatedOn = new DateTime(2024, 7, 10, 6, 32, 7, 135, DateTimeKind.Utc).AddTicks(9205),
                            ProductSizeTypeId = new Guid("b9c10a10-806c-4db3-94ac-87a9b5657442"),
                            Sort = 2,
                            UpdatedOn = new DateTime(2024, 7, 10, 6, 32, 7, 135, DateTimeKind.Utc).AddTicks(9205),
                            Value = "5M"
                        },
                        new
                        {
                            Id = new Guid("5897a1c7-2b4b-420f-9230-484b72f03d68"),
                            CreatedOn = new DateTime(2024, 7, 10, 6, 32, 7, 135, DateTimeKind.Utc).AddTicks(9207),
                            ProductSizeTypeId = new Guid("b9c10a10-806c-4db3-94ac-87a9b5657442"),
                            Sort = 3,
                            UpdatedOn = new DateTime(2024, 7, 10, 6, 32, 7, 135, DateTimeKind.Utc).AddTicks(9207),
                            Value = "6M"
                        },
                        new
                        {
                            Id = new Guid("4c2dd2eb-2a83-4424-8d97-d106ccd115d9"),
                            CreatedOn = new DateTime(2024, 7, 10, 6, 32, 7, 135, DateTimeKind.Utc).AddTicks(9209),
                            ProductSizeTypeId = new Guid("b9c10a10-806c-4db3-94ac-87a9b5657442"),
                            Sort = 4,
                            UpdatedOn = new DateTime(2024, 7, 10, 6, 32, 7, 135, DateTimeKind.Utc).AddTicks(9210),
                            Value = "7M"
                        },
                        new
                        {
                            Id = new Guid("b96b3380-5333-42f8-9a04-41474ee6fcc6"),
                            CreatedOn = new DateTime(2024, 7, 10, 6, 32, 7, 135, DateTimeKind.Utc).AddTicks(9212),
                            ProductSizeTypeId = new Guid("b9c10a10-806c-4db3-94ac-87a9b5657442"),
                            Sort = 5,
                            UpdatedOn = new DateTime(2024, 7, 10, 6, 32, 7, 135, DateTimeKind.Utc).AddTicks(9212),
                            Value = "8M"
                        },
                        new
                        {
                            Id = new Guid("4d6be206-95b2-4401-9ac6-d4471da04fd0"),
                            CreatedOn = new DateTime(2024, 7, 10, 6, 32, 7, 135, DateTimeKind.Utc).AddTicks(9216),
                            ProductSizeTypeId = new Guid("b9c10a10-806c-4db3-94ac-87a9b5657442"),
                            Sort = 6,
                            UpdatedOn = new DateTime(2024, 7, 10, 6, 32, 7, 135, DateTimeKind.Utc).AddTicks(9216),
                            Value = "10M"
                        },
                        new
                        {
                            Id = new Guid("b807319d-684d-4dec-aeb2-12e1d87fc6f7"),
                            CreatedOn = new DateTime(2024, 7, 10, 6, 32, 7, 135, DateTimeKind.Utc).AddTicks(9218),
                            ProductSizeTypeId = new Guid("b9c10a10-806c-4db3-94ac-87a9b5657442"),
                            Sort = 7,
                            UpdatedOn = new DateTime(2024, 7, 10, 6, 32, 7, 135, DateTimeKind.Utc).AddTicks(9219),
                            Value = "12M"
                        },
                        new
                        {
                            Id = new Guid("2cf00f74-908b-43dd-b5b2-87b20dbe3d32"),
                            CreatedOn = new DateTime(2024, 7, 10, 6, 32, 7, 135, DateTimeKind.Utc).AddTicks(9221),
                            ProductSizeTypeId = new Guid("b9c10a10-806c-4db3-94ac-87a9b5657442"),
                            Sort = 8,
                            UpdatedOn = new DateTime(2024, 7, 10, 6, 32, 7, 135, DateTimeKind.Utc).AddTicks(9221),
                            Value = "16M"
                        },
                        new
                        {
                            Id = new Guid("25fc86e4-19e2-47ab-933d-3b5835133ebd"),
                            CreatedOn = new DateTime(2024, 7, 10, 6, 32, 7, 135, DateTimeKind.Utc).AddTicks(9223),
                            ProductSizeTypeId = new Guid("b9c10a10-806c-4db3-94ac-87a9b5657442"),
                            Sort = 9,
                            UpdatedOn = new DateTime(2024, 7, 10, 6, 32, 7, 135, DateTimeKind.Utc).AddTicks(9223),
                            Value = "24M"
                        },
                        new
                        {
                            Id = new Guid("fd9956c7-c37c-4fdb-ad4d-8c78da5d4350"),
                            CreatedOn = new DateTime(2024, 7, 10, 6, 32, 7, 135, DateTimeKind.Utc).AddTicks(9225),
                            ProductSizeTypeId = new Guid("b9c10a10-806c-4db3-94ac-87a9b5657442"),
                            Sort = 10,
                            UpdatedOn = new DateTime(2024, 7, 10, 6, 32, 7, 135, DateTimeKind.Utc).AddTicks(9226),
                            Value = "3Y/A"
                        },
                        new
                        {
                            Id = new Guid("c2546685-c950-498c-bbb7-f560bf0cec72"),
                            CreatedOn = new DateTime(2024, 7, 10, 6, 32, 7, 135, DateTimeKind.Utc).AddTicks(9228),
                            ProductSizeTypeId = new Guid("b9c10a10-806c-4db3-94ac-87a9b5657442"),
                            Sort = 11,
                            UpdatedOn = new DateTime(2024, 7, 10, 6, 32, 7, 135, DateTimeKind.Utc).AddTicks(9228),
                            Value = "4Y/A"
                        },
                        new
                        {
                            Id = new Guid("7be0770b-23b6-4049-974b-513e70cf2428"),
                            CreatedOn = new DateTime(2024, 7, 10, 6, 32, 7, 135, DateTimeKind.Utc).AddTicks(9230),
                            ProductSizeTypeId = new Guid("b9c10a10-806c-4db3-94ac-87a9b5657442"),
                            Sort = 12,
                            UpdatedOn = new DateTime(2024, 7, 10, 6, 32, 7, 135, DateTimeKind.Utc).AddTicks(9230),
                            Value = "5Y/A"
                        },
                        new
                        {
                            Id = new Guid("24cecfc4-9827-4ebf-9120-ccd0a332f66a"),
                            CreatedOn = new DateTime(2024, 7, 10, 6, 32, 7, 135, DateTimeKind.Utc).AddTicks(9233),
                            ProductSizeTypeId = new Guid("b9c10a10-806c-4db3-94ac-87a9b5657442"),
                            Sort = 13,
                            UpdatedOn = new DateTime(2024, 7, 10, 6, 32, 7, 135, DateTimeKind.Utc).AddTicks(9233),
                            Value = "6Y/A"
                        },
                        new
                        {
                            Id = new Guid("cda752be-8933-4fb5-9737-ad00f45bc130"),
                            CreatedOn = new DateTime(2024, 7, 10, 6, 32, 7, 135, DateTimeKind.Utc).AddTicks(9237),
                            ProductSizeTypeId = new Guid("b9c10a10-806c-4db3-94ac-87a9b5657442"),
                            Sort = 14,
                            UpdatedOn = new DateTime(2024, 7, 10, 6, 32, 7, 135, DateTimeKind.Utc).AddTicks(9237),
                            Value = "7Y/A"
                        },
                        new
                        {
                            Id = new Guid("71ce9e4c-012e-4591-90bd-1c0c6b1c32d1"),
                            CreatedOn = new DateTime(2024, 7, 10, 6, 32, 7, 135, DateTimeKind.Utc).AddTicks(9239),
                            ProductSizeTypeId = new Guid("b9c10a10-806c-4db3-94ac-87a9b5657442"),
                            Sort = 15,
                            UpdatedOn = new DateTime(2024, 7, 10, 6, 32, 7, 135, DateTimeKind.Utc).AddTicks(9239),
                            Value = "8Y/A"
                        },
                        new
                        {
                            Id = new Guid("51291fb1-6bd2-46a7-aaa8-f294431e2527"),
                            CreatedOn = new DateTime(2024, 7, 10, 6, 32, 7, 135, DateTimeKind.Utc).AddTicks(9241),
                            ProductSizeTypeId = new Guid("b9c10a10-806c-4db3-94ac-87a9b5657442"),
                            Sort = 16,
                            UpdatedOn = new DateTime(2024, 7, 10, 6, 32, 7, 135, DateTimeKind.Utc).AddTicks(9241),
                            Value = "9Y/A"
                        },
                        new
                        {
                            Id = new Guid("2a5ad503-2b8a-49b1-83a8-4dd8d34ec031"),
                            CreatedOn = new DateTime(2024, 7, 10, 6, 32, 7, 135, DateTimeKind.Utc).AddTicks(9243),
                            ProductSizeTypeId = new Guid("b9c10a10-806c-4db3-94ac-87a9b5657442"),
                            Sort = 17,
                            UpdatedOn = new DateTime(2024, 7, 10, 6, 32, 7, 135, DateTimeKind.Utc).AddTicks(9243),
                            Value = "10Y/A"
                        },
                        new
                        {
                            Id = new Guid("ba2094e7-4640-4eef-b6c2-edaffd3bfc49"),
                            CreatedOn = new DateTime(2024, 7, 10, 6, 32, 7, 135, DateTimeKind.Utc).AddTicks(9245),
                            ProductSizeTypeId = new Guid("b9c10a10-806c-4db3-94ac-87a9b5657442"),
                            Sort = 18,
                            UpdatedOn = new DateTime(2024, 7, 10, 6, 32, 7, 135, DateTimeKind.Utc).AddTicks(9246),
                            Value = "11Y/A"
                        },
                        new
                        {
                            Id = new Guid("ace2c2fa-974d-4766-aa5e-c5abb09baf08"),
                            CreatedOn = new DateTime(2024, 7, 10, 6, 32, 7, 135, DateTimeKind.Utc).AddTicks(9248),
                            ProductSizeTypeId = new Guid("b9c10a10-806c-4db3-94ac-87a9b5657442"),
                            Sort = 19,
                            UpdatedOn = new DateTime(2024, 7, 10, 6, 32, 7, 135, DateTimeKind.Utc).AddTicks(9248),
                            Value = "12Y/A"
                        },
                        new
                        {
                            Id = new Guid("91c9a320-b6e6-4c3f-bd4b-6c0b257d599d"),
                            CreatedOn = new DateTime(2024, 7, 10, 6, 32, 7, 135, DateTimeKind.Utc).AddTicks(9250),
                            ProductSizeTypeId = new Guid("b9c10a10-806c-4db3-94ac-87a9b5657442"),
                            Sort = 20,
                            UpdatedOn = new DateTime(2024, 7, 10, 6, 32, 7, 135, DateTimeKind.Utc).AddTicks(9250),
                            Value = "13Y/A"
                        },
                        new
                        {
                            Id = new Guid("238011d4-bdba-4f0f-b8d4-e0a484d8c859"),
                            CreatedOn = new DateTime(2024, 7, 10, 6, 32, 7, 135, DateTimeKind.Utc).AddTicks(9252),
                            ProductSizeTypeId = new Guid("b9c10a10-806c-4db3-94ac-87a9b5657442"),
                            Sort = 21,
                            UpdatedOn = new DateTime(2024, 7, 10, 6, 32, 7, 135, DateTimeKind.Utc).AddTicks(9252),
                            Value = "14Y/A"
                        },
                        new
                        {
                            Id = new Guid("26fd8fa0-e4c0-4909-8fc3-059bfc8a46ce"),
                            CreatedOn = new DateTime(2024, 7, 10, 6, 32, 7, 135, DateTimeKind.Utc).AddTicks(9256),
                            ProductSizeTypeId = new Guid("b9c10a10-806c-4db3-94ac-87a9b5657442"),
                            Sort = 22,
                            UpdatedOn = new DateTime(2024, 7, 10, 6, 32, 7, 135, DateTimeKind.Utc).AddTicks(9256),
                            Value = "15Y/A"
                        },
                        new
                        {
                            Id = new Guid("3594dfbe-ae5c-4be6-ab0e-fd67134bf2ff"),
                            CreatedOn = new DateTime(2024, 7, 10, 6, 32, 7, 135, DateTimeKind.Utc).AddTicks(9258),
                            ProductSizeTypeId = new Guid("b9c10a10-806c-4db3-94ac-87a9b5657442"),
                            Sort = 23,
                            UpdatedOn = new DateTime(2024, 7, 10, 6, 32, 7, 135, DateTimeKind.Utc).AddTicks(9259),
                            Value = "16Y/A"
                        });
                });

            modelBuilder.Entity("Troonch.Sales.Domain.Entities.ProductSizeType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<DateTime>("UpdatedOn")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("ProductSizeTypes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b9c10a10-806c-4db3-94ac-87a9b5657442"),
                            CreatedOn = new DateTime(2024, 7, 10, 6, 32, 7, 135, DateTimeKind.Utc).AddTicks(8849),
                            Name = "Abiti - Completi - Vestiti - Bambino/a",
                            UpdatedOn = new DateTime(2024, 7, 10, 6, 32, 7, 135, DateTimeKind.Utc).AddTicks(8849)
                        },
                        new
                        {
                            Id = new Guid("2870acf6-f145-4714-95b6-168588555c32"),
                            CreatedOn = new DateTime(2024, 7, 10, 6, 32, 7, 135, DateTimeKind.Utc).AddTicks(8852),
                            Name = "Abiti - Vestiti - Uomo/Donna",
                            UpdatedOn = new DateTime(2024, 7, 10, 6, 32, 7, 135, DateTimeKind.Utc).AddTicks(8852)
                        },
                        new
                        {
                            Id = new Guid("bac9f80e-c261-4d89-8124-9a5c52819828"),
                            CreatedOn = new DateTime(2024, 7, 10, 6, 32, 7, 135, DateTimeKind.Utc).AddTicks(8854),
                            Name = "Accessori",
                            UpdatedOn = new DateTime(2024, 7, 10, 6, 32, 7, 135, DateTimeKind.Utc).AddTicks(8854)
                        },
                        new
                        {
                            Id = new Guid("3e13d40c-6b24-4c7f-90fc-d5654e42a2a1"),
                            CreatedOn = new DateTime(2024, 7, 10, 6, 32, 7, 135, DateTimeKind.Utc).AddTicks(8885),
                            Name = "Scarpe Bambino/a",
                            UpdatedOn = new DateTime(2024, 7, 10, 6, 32, 7, 135, DateTimeKind.Utc).AddTicks(8885)
                        },
                        new
                        {
                            Id = new Guid("519c79e9-5444-4109-bec6-44eec7235ba5"),
                            CreatedOn = new DateTime(2024, 7, 10, 6, 32, 7, 135, DateTimeKind.Utc).AddTicks(8889),
                            Name = "Scarpe Uomo/Donna",
                            UpdatedOn = new DateTime(2024, 7, 10, 6, 32, 7, 135, DateTimeKind.Utc).AddTicks(8889)
                        });
                });

            modelBuilder.Entity("Troonch.Sales.Domain.Entities.ProductTag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("UpdatedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("ProductTag");
                });

            modelBuilder.Entity("Troonch.Sales.Domain.Entities.ProductTagLookup", b =>
                {
                    b.Property<Guid>("ProductId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("TagId")
                        .HasColumnType("char(36)");

                    b.HasKey("ProductId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("ProductTagLookup");
                });

            modelBuilder.Entity("Troonch.Sales.Domain.Entities.Product", b =>
                {
                    b.HasOne("Troonch.Sales.Domain.Entities.ProductBrand", "ProductBrand")
                        .WithMany("Products")
                        .HasForeignKey("ProductBrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Troonch.Sales.Domain.Entities.ProductCategory", "ProductCategory")
                        .WithMany("Products")
                        .HasForeignKey("ProductCategoryId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Troonch.Sales.Domain.Entities.ProductGender", "ProductGender")
                        .WithMany("Products")
                        .HasForeignKey("ProductGenderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Troonch.Sales.Domain.Entities.ProductMaterial", "ProductMaterial")
                        .WithMany("Products")
                        .HasForeignKey("ProductMaterialId");

                    b.Navigation("ProductBrand");

                    b.Navigation("ProductCategory");

                    b.Navigation("ProductGender");

                    b.Navigation("ProductMaterial");
                });

            modelBuilder.Entity("Troonch.Sales.Domain.Entities.ProductCategory", b =>
                {
                    b.HasOne("Troonch.Sales.Domain.Entities.ProductSizeType", "ProductSizeType")
                        .WithMany("ProductCategories")
                        .HasForeignKey("ProductSizeTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductSizeType");
                });

            modelBuilder.Entity("Troonch.Sales.Domain.Entities.ProductGenderSizeTypeLookup", b =>
                {
                    b.HasOne("Troonch.Sales.Domain.Entities.ProductGender", "ProductGender")
                        .WithMany("ProductSizeTypes")
                        .HasForeignKey("ProductGenderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Troonch.Sales.Domain.Entities.ProductSizeType", "ProductSizeType")
                        .WithMany("ProductGenders")
                        .HasForeignKey("ProductSizeTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductGender");

                    b.Navigation("ProductSizeType");
                });

            modelBuilder.Entity("Troonch.Sales.Domain.Entities.ProductItem", b =>
                {
                    b.HasOne("Troonch.Sales.Domain.Entities.Product", "Product")
                        .WithMany("ProductItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Troonch.Sales.Domain.Entities.ProductSizeOption", "ProductSizeOption")
                        .WithMany("ProductItems")
                        .HasForeignKey("ProductSizeOptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("ProductSizeOption");
                });

            modelBuilder.Entity("Troonch.Sales.Domain.Entities.ProductSizeOption", b =>
                {
                    b.HasOne("Troonch.Sales.Domain.Entities.ProductSizeType", "ProductSizeType")
                        .WithMany("ProductSizeOptions")
                        .HasForeignKey("ProductSizeTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductSizeType");
                });

            modelBuilder.Entity("Troonch.Sales.Domain.Entities.ProductTagLookup", b =>
                {
                    b.HasOne("Troonch.Sales.Domain.Entities.Product", "Product")
                        .WithMany("ProductTags")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Troonch.Sales.Domain.Entities.ProductTag", "ProductTag")
                        .WithMany("ProductTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("ProductTag");
                });

            modelBuilder.Entity("Troonch.Sales.Domain.Entities.Product", b =>
                {
                    b.Navigation("ProductItems");

                    b.Navigation("ProductTags");
                });

            modelBuilder.Entity("Troonch.Sales.Domain.Entities.ProductBrand", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("Troonch.Sales.Domain.Entities.ProductCategory", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("Troonch.Sales.Domain.Entities.ProductGender", b =>
                {
                    b.Navigation("ProductSizeTypes");

                    b.Navigation("Products");
                });

            modelBuilder.Entity("Troonch.Sales.Domain.Entities.ProductMaterial", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("Troonch.Sales.Domain.Entities.ProductSizeOption", b =>
                {
                    b.Navigation("ProductItems");
                });

            modelBuilder.Entity("Troonch.Sales.Domain.Entities.ProductSizeType", b =>
                {
                    b.Navigation("ProductCategories");

                    b.Navigation("ProductGenders");

                    b.Navigation("ProductSizeOptions");
                });

            modelBuilder.Entity("Troonch.Sales.Domain.Entities.ProductTag", b =>
                {
                    b.Navigation("ProductTags");
                });
#pragma warning restore 612, 618
        }
    }
}
